### ISSUE TITLE
Lorsqu'on se déconnecte, à la suite d’une mauvaise requête, le menu de gauche demeure accessible, la partie principale de la page nous redirige vers le login.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#184]
Pour reproduire le bogue:
1. Naviguer à l'onglet "Bâtiments" dans le "Tableau de bord".
2. Ouvrir le menu principal.
3. Créer un nouveau lot quelconque.
4. Assigner un nouvel inspecteur.
5. Cocher "Prêt pour l'inspection".
6. Cliquer sur "Sauvegarder".

**Comment by philipperobertgh** [comment]
Nouvelle gestion des erreurs a été mise en place pour rester dans le même formulaire lors d'une erreur de requête, avec affichage d'un message de guidage usager générique.
Pas réussit à reproduire le schma du bogue présenté, cependant même en forcant une erreur de requête la nouvelle gestion d'erreur ne nous redirige plus vers le login.
