### ISSUE TITLE
Lorsqu’on essaie de modifier l’information d’un bâtiment, l’information n’est pas enregistrée dans la base de données.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#186]
1. Se rendre sur la page "Bâtiments" à partir du menu principal.
2. Cliquer pour éditer un bâtiment quelconque.
3. Essayer de modifier le code postal du bâtiment. L'information ne sera pas enregistrée et/ou l'application plantera.

**Comment by philipperobertgh** [comment]
Testé et non repropduit avec la nouvelle gestion des erreurs.
