### ISSUE TITLE
Latence lors du changement d'onglets du menu.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#192]
Peut-être utiliser une cache pour afficher l’information déjà recueillie pendant que la requête au serveur s’effectue en arrière-plan.

**Comment by iamkinetic** [comment]
@mickjol Qu'en penses-tu?

**Comment by mickjol** [comment]
Je commencerais par utiliser le OData pour les pages (bâtiment en autre) qui sont plus longue à charger avant une cache.

**Comment by iamkinetic** [comment]
@mickjol Le menu est lent parce qu'on load les données de la page avant d'afficher ce menu?

**Comment by iamkinetic** [comment]
On va oublier l'idée de mettre une cache et on va régler les pages lentes au cas par cas en utilisant OData et ajoutant un filtre par ville un peu partout.
