### ISSUE TITLE
Il faudrait pouvoir ajouter des bâtiments à un lot existant à partir du tableau de bord.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#193]
Pour l'instant, il est uniquement possible de créer un nouveau lot à partir de l'onglet "Bâtiment" du tableau de bord.

**Comment by iamkinetic** [comment]
Est-ce une demande de quelqu'un?

**Comment by julandry** [comment]
C'est un point que nous avons soulevé avec Jocelyn lors de la mise sur pied du premier projet pilote.

**Comment by iamkinetic** [comment]
Comme nous avons déjà sortie la liste des fonctionnalités que nous voulons avoir pour la version 1, je vais me permettre de laisser ça dans le backlog et on verra plus tard ce qu'on en fait.

**Comment by iamkinetic** [comment]
@jocelyncardinal  Est-ce vraiment utile?  Je ne vois pas vraiment comment ça peut être plus simple que d'aller dans le lot lui-même et ajouter les bâtiments par là.

**Comment by iamkinetic** [comment]
Je vais me permettre de fermer ce point et on le réouvrira lorsqu'on aura une demande et solution claire.
