### ISSUE TITLE
Incohérence entre la façon de filtrer les données des bâtiments dans l’onglet « Bâtiments » du tableau de bord et de celui du menu principal

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#194]
Dans le tableau de bord il faut tapper ce que l'on veut rechercher et cette recherche s'applique sur tous les champs.
Alors que dans "Bâtiments" du menu principal, il est possible de filtrer les résultats en sélectionnant une hiérarchie de ville et de rue.

**Comment by iamkinetic** [comment]
Le bâtiment du menu principal sert à la gestion des bâtiments alors que le tableau de bord a une utilité autre qui est de gérer les inspections..  C'est la raison de la différence dans la façon de naviguer.
