### ISSUE TITLE
Dans certaines situations, il y a l'icône d'une poubelle pour supprimer un item alors qu'à d'autres endroits, c'est un "X". Il faudrait peut-être uniformiser le tout.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#195]
Exemple :
 - Poubelle dans l'onglet "Inspection en cours/ en attente" lorsqu'on veut supprimer un lot.
 - "X" lorsqu'on veut supprimer une question d'un questionnaire.

**Comment by iamkinetic** [comment]
Allons y avec la poubelle, c'est ce qu'on a mis partout dans l'application mobile.

**Comment by iamkinetic** [comment]
@julandry à quel endroit tu as vu des "X" au juste?

**Comment by julandry** [comment]
La seule place c'est dans le document question.component.html:
            <dx-button icon="remove" (onClick)="onRemoveQuestion()"></dx-button>
