### ISSUE TITLE
Possibilité de revoir les données d'une inspection après l'avoir approuvée.

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#197]
Dans le tableau de bord, sous la section inspections complétées, il pourrait être pertinent d’avoir une vue semblable à celle qu’on obtient lorsqu’on doit approuver une inspection. Cela permettrait d’aller revoir l’intégralité de l’information recueillie dans une inspection (ceci est différent du rapport PDF, parce que celui-ci présentera une version filtrée des informations).

**Comment by iamkinetic** [comment]
C'est effectivement prévu, mais on dirait bien que nous n'avons jamais créé le point pour ça.

Sur un bâtiment, nous pourrons voir la liste des inspections qu'il y a eu et consulter ces inspections en read only.

**Comment by iamkinetic** [comment]
v1 ou v2?  À déterminer.

**Comment by iamkinetic** [comment]
En même temps, on peut se demander comment on va faire ça puisque la copie sur laquelle est fait une inspection est supprimée lorsque l'inspection est acceptée.

Est-ce dans la fiche du bâtiment qu'on devrait voir ça?
