### ISSUE TITLE
Ajouter l'outil de croquis pour le traitement des images

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip#201]

**Comment by iamkinetic** [comment]
Qu'est-ce que cet issue exactement?  C'est un peu vague.

**Comment by iamkinetic** [comment]
@AudreyLR Michael va faire le pull request de #69 aujourd'hui ou tôt demain.  Tu pourrais te faire une branche par dessus la sienne pour commencer ce point si tu es rendue là et qu'on a pas encore mergé.

**Comment by AudreyLR** [comment]
Parfait!

>

**Comment by iamkinetic** [comment]
Attendre que les pull request de #62 soient merged avant de tester ceci svp.
