### ISSUE TITLE
Rapport - Grille pour gérer les templates

### ISSUE THREAD

**Issue by julandry** [CAUCA-9-1-1/survip#204]
Ajout, modification, suppression dans la liste complètes des rapports

**Comment by iamkinetic** [comment]
Faire #88 et #201 avant ceci.

**Comment by iamkinetic** [comment]
@AudreyLR Ce point là est-il vraiment en cours?

**Comment by AudreyLR** [comment]
Oui, mais pas encore fonctionnel

**Comment by jocelyncardinal** [comment]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/06ed34ba-7ddb-47b0-a9a4-0a263e57fd12)

**Comment by iamkinetic** [comment]
Si on doit attendre les projets pilotes, je propose qu'on n'ajoute pas la colonne SSI si elle n'est pas déjà là.

**Comment by jocelyncardinal** [comment]
Configuration des rapport - Distinguer rapports par SSI (colonnes SSI) #426
