### ISSUE TITLE
Rapport – Une granularité plus fine de certain PlaceHolder pourrait être éventuellement développé 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#242]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/bd0d252d-e8a6-426f-a9e5-d58fe90ce88e)

**Comment by iamkinetic** [comment]
Je suis déjà en train d'ajouter de la granularité.  On ne pourra plus mettre `{{Anomalies}}` pour afficher les anomalies dans un rapport. Il faudra être un peu plus précis, exemple:
`
[Anomaly]
Thèmes: {{Theme}}
Commentaires: {{Notes}}
Photos:
   [AnomalyPicture]
      {{PictureData}}
   [/AnomalyPicture]
[/Anomaly]
`

**Comment by iamkinetic** [comment]
Sera fait en partie ou en totalité dans le cadre de cet issue: CAUCA-9-1-1/survip-webapi#102

Point à réviser quand celui-ci sera complété.

**Comment by jocelyncardinal** [comment]
Parfait!

De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip <reply@reply.github.com>
Date : jeudi 30 août 2018 18:11
À : CAUCA-9-1-1/survip <survip@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip] Rapport – Une granularité plus fine de certain PlaceHolder pourrait être éventuellement développé (#242)


Je suis déjà en train d'ajouter de la granularité. On ne pourra plus mettre {{Anomalies}} pour afficher les anomalies dans un rapport. Il faudra être un peu plus précis, exemple:
[Anomaly] Thèmes: {{Theme}} Commentaires: {{Notes}} Photos: [AnomalyPicture] {{PictureData}} [/AnomalyPicture] [/Anomaly]
