### ISSUE TITLE
Rapport – Capacité de rendre certain rapport disponible lors de l’intervention 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#244]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4c57a7f1-c309-4cd9-99ce-75374514bdbd)

**Comment by iamkinetic** [comment]
Est-ce que de faire un rapport d'intervention entre vraiment dans le cadre du projet SURVI-Prévention?

**Comment by jocelyncardinal** [comment]
Non pas vraiment c’est plus un « nice-to-have » qui a été proposé comme feedback … donc pas dans la version V1 … l’idée serait de transmettre le PDF généré (et désigné par le SSI) directement au serveur de Cauca pour qu’il puisse être utilisé lors de l’intervention. Ca pourrait entrer dans le cadre du « Transfer de l’info d’inspection à CAUCA » pour être utilisé lors des interventions.

[cid:image001.jpg@01D4408F.09850300]



De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip <reply@reply.github.com>
Date : jeudi 30 août 2018 18:07
À : CAUCA-9-1-1/survip <survip@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip] Rapport – Capacité de rendre certain rapport disponible lors de l’intervention (#244)


Est-ce que de faire un rapport d'intervention entre vraiment dans le cadre du projet SURVI-Prévention?

**Comment by iamkinetic** [comment]
Ok.  Ce sera donc pour une version ultérieure.

@Zalverick Que penses-tu de l'idée d'importer les PDFs des fiches des bâtiments comme on le fait avec PL?

**Comment by jocelyncardinal** [comment]
Oui, c’est ça l’idée, simplement importer le PDF et ensuite le rendre disponible (aucun traitement à faire).  Notez que ce n’est clairement pas quelques choses d’attendu pour la V1 (version ultérieure seulement)

De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip <reply@reply.github.com>
Date : vendredi 31 août 2018 08:50
À : CAUCA-9-1-1/survip <survip@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip] Rapport – Capacité de rendre certain rapport disponible lors de l’intervention (#244)


Ok. Ce sera donc pour une version ultérieure.

@Zalverick<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZalverick&data=02%7C01%7C%7Cc8555bd8ab6d43f4bdee08d60f4042d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636713165996971009&sdata=62Qh%2FU93qKbZF8KLdigylleKWYdKuj8aKIvfpCgW0Ms%3D&reserved=0> Que penses-tu de l'idée d'importer les PDFs des fiches des bâtiments comme on le fait avec PL?

**Comment by iamkinetic** [comment]
@jocelyncardinal On a parlé de ça aujourd'hui dans notre rencontre de sprint et c'est quelque chose qu'on va faire avant de passer aux plans d'intervention, donc dans les prochaines semaines.  On veut que les trucs suivants soient exportés vers le logiciel CAUCA pour être disponible pour les répartiteurs, SURVI-Mobile, SURVI-Prévention, etc:
* Contacts.
* Pnaps.
* Matières dangereuses.
* Peut-être certains champs du bâtiment (on a en réalité pas le moindre champ du bâtiment du logiciel CAUCA qui est modifiable lors d'une inspection, mais on va probablement ajouter la rue transversale parce que semble-t-il que c'est une demande de certains clients déjà).
* Et la fiche d'intervention en PDF de SURVI-Prévention qui viendra prendre la place de celle par défaut de CAUCA.

Nous n'avons pas l'intention d'importer les autres tables tant qu'on aura pas fait les plans d'intervention.

**Comment by iamkinetic** [comment]
Il restera quand même à faire des modifications pour avoir clairement UN rapport à exporter vers CAUCA pour un SSI.

**Comment by iamkinetic** [comment]
Voir epic Cauca-9-1-1/survip-webapi#241
