### ISSUE TITLE
Modification de l’information d’un bâtiment ne fonctionne (pas sauvegardé)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#245]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/af927cb1-b882-4cee-b0d3-ec469353f50d)

**Comment by iamkinetic** [comment]
Ah!  On a remarqué ça aussi!  Je pense que c'est depuis que j'ai mis le bon type à la colonne de la coordonnée du bâtiment que ça fait ça.

**Comment by iamkinetic** [comment]
@mickjol Tout est ok dans la page web, mais il y a quelques changements à faire dans l'API même si tout fonctionne.
