### ISSUE TITLE
Changer les informations obligatoire pour une borne

### ISSUE THREAD

**Issue by mickjol** [CAUCA-9-1-1/survip#251]
Mettre un opérateur par défaut et mettre les unités de mesure et les quantités optionnelles.

**Comment by iamkinetic** [comment]
Enlever le modèle "OperatorType" et remplacer par un enum.

Le premier choix de l'enum sera la valeur par défaut.

Puis mettre les champs de quantité en decimal nullable (rateFrom, rateTo, pressureFrom, pressureTo).

Ne pas modifier la structure BD directement, on va le faire par la migration.
