### ISSUE TITLE
Filtre du dashboard pour les inspections les noms similaires même pour des inspections différentes

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#271]
Exemple : Prendre deux inspections différentes ville et batiment et leur donner le même nom.
-> Un seul lot d'inspection apparait dans le dashboard et lorsque l'on clique voir un seul batiment est disponible
-> résultat on ne peut pas accéder à l'autre inspection.
Voir à ajouter le idinspection dans le regroupement de la grille

**Comment by iamkinetic** [comment]
Bonne trouvaille!
