### ISSUE TITLE
Different API errors in SURVIP (tests)

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#272]
* /api/Authentification/SessionStatus:1 Failed to load resource: the server responded with a status of 401 ()
** This should be removed.
* https://survipreventiontest.cauca.ca/api/City/45b9d1be-c321-11e8-9a53-525400cc3eb9/geolocation returns an error 500.

**Comment by mickjol** [comment]
L'erreur sur le SessionStatus est une information afficher par le navigateur.
Le code affichage aucune information par lui-même dans la console.

Pour ne pas afficher cela, la requête "SessionStatus" devrait retourne 200 avec "true" ou "false"

**Comment by mickjol** [comment]
Pour l'erreur de géolocation sur la ville, c'est le serveur qui bloquait l'accès. Le serveur à maintenant accès d'aller sur internet.
