### ISSUE TITLE
Valider si on peut augmenter la qualité de l'image annotée via sketch-tool

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#291]
Il semble que la résolution de la photo en prend un coup après l'avoir annoté avec Sketch-Tool:

Exemple :
* Avant: 
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/d42349d6-12db-4463-95d5-0d525d8bf93e)

* Après:
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/ffa55f62-2c8d-4e3f-8b43-57159eb726e5)

Voir si on pourrait améliorer ça.  Idéalement, on ne perdrait pas de qualité.

**Comment by iamkinetic** [comment]
SVP, mettre un estimé de temps pour ce point sur ZenHub.

**Comment by iamkinetic** [comment]
Est-ce qu'il y a de l'espoir?

**Comment by AudreyLR** [comment]
Oui, même si ça ajoute quelques étapes pour l'enregistrement.

**Comment by iamkinetic** [comment]
Est-ce que ce sera aussi fait pour le mobile?

**Comment by iamkinetic** [comment]
@AudreyLR  Très bon travail, c'est vraiment mieux!  Reste juste à voir s'il faut également mettre ça dans le mobile, puis j'accepterai le pull request.

Est-ce que le code que tu as ajouté devrait être dans Sketch-Tool directement pour éviter de refaire la même chose partout?

**Comment by AudreyLR** [comment]
En effet, l'image enregistrée présentement par l'application mobile a le même problème.

Je faisais la conversion directement dans l'application mobile pour éviter de recalculer plusieurs fois la version haute qualité ou maintenir deux canvas en même temps. Par contre c'est sûr que ça aurait l'avantage d'éviter de refaire le processus dans l'application mobile.
Dans ce cas, est-ce qu'on préfère donc laisser la conversion à la libraire et éviter la duplication, où mettre faire la conversion dans le Web et mobile seulement lorsqu'on enregistre pour que ce soit plus performant?
