### ISSUE TITLE
Problème avec l'alignement de la boite de crop par rapport à la position du curseur

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip#294]
La boite de crop est désalignée par rapport à la souris.

**Comment by iamkinetic** [comment]
@AudreyLR Est-ce que tu réussis à faire afficher les images du mobile dans l'approbation de ton côté?  Ça ne fonctionne pas du tout du mien et ça ne semble pas lié à tes changements de cette branche parce que ça donne le même résultat dans la branche master.

**Comment by iamkinetic** [comment]
@AudreyLR 

Je ne sais pas si les bugs que j'ai trouvé ont rapport avec le changement ou s'ils étaient déjà là:

J'entre dans une photo et je dessine.  Je sors.  À chaque fois que j'entre et ressors, le dessin vient de plus en plus petit.

J'ai aussi eu le cas où le dessin gardait sa taille originale, mais que la photo était zoomed in à chaque fois que j'entrais/sortais du sketch-tool.

Pour l'instant, je ne rejette pas ton pull request parce qu'on a clairement plein de nouveaux problèmes de notre côté aux niveaux des images et que ça ne donne rien de corriger ça tant que nos problèmes ne sont pas corrigés.

Voir le #366.
