### ISSUE TITLE
Créer un usager Zenhub pour Alexandre Labbe (QA)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#295]
Cela permettrait a Alexandre de créer des issue dans le backlog lorsqu'il trouve des bug ...

**Comment by iamkinetic** [comment]
Il doit d’abord se créer un usager sur github.  Des ce moment il pourra créer des issues dans les repos du site web et du mobile.  L’acces à ZenHub c’est plus pour qu’il voit l’avancement et sur quel point on travaille.

**Comment by iamkinetic** [comment]
Invitation envoyée.
