### ISSUE TITLE
Amélioration du SketchTools

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#296]
Il faudrait avoir un bouton annuler pour fermer sans sauvegarder :
Si j'ai fait plusieurs modifications et je ne veux pas aller les enelver une par une avant de fermer.

L'action rogner semble définitive(pas d'annulation possible) et la zone de rognage n'est pas bien controlée(#294).
La selection ne se fait pas au bon endroit et semble entrer en conflit avec l'action de selection de composant dans le dessin.
 -> un bouton annuler pour cette action est essentiel
 -> étrangement elle ne semble pas sauvegarder la selection rognée
![selection rognée.png](https://images.zenhubusercontent.com/5ae731e74b5806bc2bd12cbb/d5c66097-4b56-4916-9f6d-f90b48d8e8dd)
![même plan réouvert.png](https://images.zenhubusercontent.com/5ae731e74b5806bc2bd12cbb/fae4b29e-d22a-4a21-99da-b1faf135c6d5)

Ajouter des tool tip pour les boutons car certains ne sont pas explicites:
 Exemple: les flèches haut bas ???

Valider également qu'on ne puisse pas avoir deux boutons sélectionnés en même temps si ce n'est pas logique (note de Fred: cette demande vient des tests d'Alexandre et je ne suis pas trop sûr de ce que ça veut dire...).

**Comment by AudreyLR** [comment]
Pour ce qui est du rogner, c'est déjà couvert par l'issue #294.

**Comment by philipperobertgh** [comment]
Ok




Télécharger Outlook for Android







On Fri, Oct 12, 2018 at 2:15 PM -0400, "Audrey Lebel-Richardson" <notifications@github.com> wrote:












Pour ce qui est du rogner, c'est déjà couvert par l'issue #294.

**Comment by iamkinetic** [comment]
@AudreyLR SVP, mettre un estimé de temps pour ce point sur ZenHub.

**Comment by iamkinetic** [comment]
Par rapport au truc qui vient d'Alexandre, voici un screenshot qui explique le problème:

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/956bc663-729c-4ad7-a48b-e2a4344a93e5)

Il a le crayon et la sélection en même temps ce qui donne un drôle de résultat.

**Comment by jocelyncardinal** [comment]
Audrey, je propose de faire un épic
