### ISSUE TITLE
Tableau de Bord - "Boutons invisibles"

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#297]
Quand on se branche sur la page https://survipreventiontest.cauca.ca/#/inspection/dashboard, au haut de l page, nous avons les boutons.  Si on navigue à gauche ou à droite de ses boutons (à la même hauteurs), le curseur de la souris se modifie, comme si des boutons invisibles étaient là, mais impossible de cliquer dessus![Boutons Invisibles.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/86f78b10-fe94-4db8-94db-b95385e1b00a)

**Comment by alexandrelabbe** [comment]
En langage plus clair.. il se passe quoi?  Won't fix ou sera 0k dans prochaine version du site web?

**Comment by philipperobertgh** [comment]
Le statut de la demande est fermée donc il est considéré comme corrigé et sera disponible dans la prochaine version. 
Si une demande est fermée et non corrigée pour une raison quelconque celle-ci doit-être signifiée dans la demande.
