### ISSUE TITLE
Tableau de Bord - Cellule "Niveau de risque"

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#298]
Si on sélectionne un niveau de risque, un message d'erreur nous est affiché:![CelluleNiveauRisque.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/63772d8d-a203-4167-b48d-88c320bd91d1)

**Comment by alexandrelabbe** [comment]
Question: Serait-il possible / bon de pouvoir sélectionner plus d'un niveau de risque à la fois?

**Comment by iamkinetic** [comment]
Pour développeur, voir ceci pour des pistes de solution :
* https://www.devexpress.com/Support/Center/Question/Details/T410004/dxdatagrid-how-to-display-multiple-values-in-a-lookup-column-using-dxtagbox
* https://www.devexpress.com/Support/Center/Question/Details/T124057/dxdatagrid-provide-the-capability-to-customize-a-cell-in-a-filter-row

**Comment by iamkinetic** [comment]
Et voir ceci pour le bug de filtre : 
* https://www.devexpress.com/Support/Center/Question/Details/T433584/dxdatagrid-throws-the-a-binary-operator-with-incompatible-types-was-detected-error-when

**Comment by iamkinetic** [comment]
Ok, j'ai corrigé le bug, mais je n'ai pas réussi à transformer le filtre pour permettre la multi-sélection.

@Jocelyncardinal Si tu veux avoir la possibilité de sélectionner plus d'un niveau de risque dans le tableau de bord, tu pourras créer un nouveau point et on se permettra alors de passer plus de temps là dessus.
