### ISSUE TITLE
Tableau de bord - Voie de circulation

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#300]
1 - Il est possible de faire des recherches en entrant des cararctères autres que Alpha Numérique

2 - Une ligne "vide" est affichée dans le choix des voies de circulation

3 - Certaines voies de circulation apparaissent à plus d'une reprise dans la liste des choix

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/1c84db6a-e323-4b03-a1cd-4be61e2c430a)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/bcae9f88-1ba4-4749-9e0f-0a927d851908)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/b57a2a64-4131-4b28-a043-38f68c7ee574)

**Comment by iamkinetic** [comment]
* Probablement que les rues multiples sont en réalité les rues du même nom dans différentes villes.  On devrait probablement afficher le nom de la ville dans le drop down.
* On a effectivement une rue sans nom en BD.  La rue existe en Prod dans la RAO, mais elle est inactive.  On en fera pas de cas parce qu'on a ajouté les données dans la BD de prévention manuellement pour les tests, mais on ne va rien garder de tout ça.

**Comment by iamkinetic** [comment]
Je suis pas mal certain qu'on peut créer une rue avec le nom "$%&*" dans la RAO si on le veut, donc on a pas trop le choix d'aussi le permettre dans la recherche.

**Comment by alexandrelabbe** [comment]
Je crois qu'aucune voie de circulation au Québec contient de symboles

http://www.toponymie.gouv.qc.ca/ct/toposweb/recherche.aspx

**Comment by iamkinetic** [comment]
Nous allons ajouter la ville dans la boîte déroulante. Voir: CAUCA-9-1-1/survip#318
