### ISSUE TITLE
Tableau de bord - Cellule Code Postal

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#304]
1 - Il est possible d'entrer des caractères autres que Alpha Numérique dans cette cellule

2 - Il est possible d'entrer plus que 6 caractères dans cette cellule (7 si on ajoute une espace)

3 - Cette colonne est vide, si on tri croissant, décroissant, reste vide
     Si on va dans l'onglet "Bâtiment", la colonne est vide également, si on tri croissant et décroissant, les codes s'affichent

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/33f9835b-b63c-4097-b620-35b23b0ad1fc)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/50afed87-663c-4518-8e38-7c3a16b9f90a)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/bf82a67e-bfb2-48c9-9fba-9dfe21b17fa6)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/bb886676-ea00-429b-8b15-05bb0c0e9a13)

**Comment by iamkinetic** [comment]
Il y a 1263798 batiments sans code postal en PROD.   C'est ce qui donne l'impression que le code postal ne s'affiche pas.

Encore une fois, nous laisserons le filtre comme il est actuellement.
