### ISSUE TITLE
Tableau de Bord - Cellule Lot

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#305]
Doit-on avoir accès à cette sélection dans tous les menus?
Quelle soit sélectionné ou non n'a aucune influence sur l'affichage en cours:

**Comment by iamkinetic** [comment]
C'est parce qu'en réalité la valeur de la colonne est toujours affichée dans ta capture.

On peut voir que la grille est groupée par # de lot et la grille cache automatiquement la colonne sur laquelle elle est groupée.
