### ISSUE TITLE
Tableau de bord - Cellule Dernière inspction

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#307]
1 - La date doit être entrée sous la forme JJ/MM/AAAA, serait-il possible, afin d'assister lors de recherche, de faire apparaitre "ce format" dans la cellule

2 - Il est possible, quand on fait une recheche "Entre", d'entrer une date de fin supérieur à la date de début

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/2441dc3c-8256-4e2e-995f-8c0a980d02b4)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/26d19a33-b4c0-480a-9e72-702235610ce9)

**Comment by iamkinetic** [comment]
Ok.  Sera fait via  CAUCA-9-1-1/survip#318.
