### ISSUE TITLE
Tableau de bord - Cellule Photo

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#311]
Il est possible d'entrer des caractères autres qu'Alphanumérique dans cette cellule, est-ce 0k ainsi?

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/c7f83fa4-6f07-4c4b-a6b4-2ee1824de759)

**Comment by iamkinetic** [comment]
On va soit bloquer le filtre ou carrément enlever la colonne.

Via CAUCA-9-1-1/survip#318
