### ISSUE TITLE
Tableau de bord - Cellule Valeur du bâtiment

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#312]
1 - Si on entre une valeur dans la cellule de recherche, un message d'erreur nous est affiché

2 -Il est possible d'entrer des caractères autres que numrique dans cette cellulaire

~~3 - Il est possible d'entrer des nombres autre que "entier"~~

4 - Il est possible d'entrer des nombres négatifs dans cette cellule

~~5 - Devrait-on afficher la devise pour cette cellule/colonne ($ CAD) ?~~

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/af68b628-f502-45ed-b21e-d74397e2a788)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/a4bc7846-24d0-44ea-a5a0-6cf603d8f508)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/86da5dc8-95a0-4f13-b662-b1e839a2ac08)
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/622aaad6-282d-40e7-aec4-c6c52c89546f)

**Comment by iamkinetic** [comment]
Nous n'avons pas de notion de devise dans aucun des logiciels CAUCA, donc ce serait incorrect de notre part de mettre CAD comme devise dans un logiciel open source.

Le reste devra être fait.

**Comment by iamkinetic** [comment]
La colonne permet les valeurs décimales, donc il est correct de permettre les valeurs non entières.

**Comment by philipperobertgh** [comment]
Corrigé dans le #316 avec les validations de champs numérique
