### ISSUE TITLE
Tableau de bord - Cellule Matricule

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#315]
1 - Il est possible d'entrer des caractères autre que numériques dans cette cellule

2 - Il est possible d'entrer plus de 18 caractères dans cette cellule, devrait-on la barrer à 18 caractères numériques

3 - Il est possible d'entrer une valeur négative dans cette cellule

4 - Il est possible d'entrer des nombre non entier dans cette cellule

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/a08a7e5f-df25-4d50-b302-f61860da8c75)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/96574077-24c0-40bb-8821-b7c8277d5ea2)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/39605cf8-f73c-4c05-918b-943003b76da7)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/f79b6e42-3f8e-4150-88cc-a32467c6879c)

**Comment by iamkinetic** [comment]
Je ne peux pas dire que ça me dérange qu'on permette plus de chose que logique dans un filtre.  Si c'était la fenêtre de création de bâtiment, je dirais qu'il faut effectivement renforcer la validation, mais ce cas-là...

Qu'en penses-tu @JocelynCardinal ?

**Comment by alexandrelabbe** [comment]
Pour ma part, si un client fait une recherche par matricule, afin d'aider à éviter des erreurs/fautes de frappes, je crois qu'il serait utile de bloquer le nombre de caractères qu'on peut entrer dans la cellule

**Comment by jocelyncardinal** [comment]
Effectivement, je suis d’accord avec le commentaire de iamkinetic … l’important est que le site ne « gèle pas » à cause qu’on aurait entré de quoi de très bizarre. Donc, pour l’instant je recommande de ne pas mettre trop d’énergie sur cette issue quand même assez mineure …
