### ISSUE TITLE
Tableau de bord - Cellule Nombre d'appartement

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#316]
~~1 - Contrairement aux autres cellules, le texte et la recherche sont alignés à droite.  Les autres cellules sont alignées à gauche~~

2 - Si ça change quelque chose, dans cette cellule, il est possible d'entrer les caractères suivants:
. (point) , (virgule) + - e E   Si on sort du champ de recherche, la cellule "se vide"

3 - Si on entre 11 caractères ou plus dans la cellule de recherche, un message d'erreur nous est retournée (Devrait-on vérouiller le nombre maximum de caractère qu'il est possible d'entrer dans la cellule de recherche?)

4 - Si on fait une recheche par "nombre situé entre", il est possible de mettre un nombre de fin inférieur au nombre du début

5 - Suite au point #4, la cellule de recheche, le texte est maintenant aligné à gauche.  Est-ce 0k ains?

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/6d6bd7cb-f883-4904-8f95-368136d97812)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/fdbd92d9-3551-4075-a570-7867f26f24ea)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/1a258356-bd13-4145-9881-9878fc6029b4)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/c4618a6a-098f-48d1-9828-f33f38889759)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/7e0b72d8-4d02-4273-ac3e-376bdeaeb668)

**Comment by alexandrelabbe** [comment]
Les situations mentionnée ci-haut se répètent pour les cellules:
-Nombre de bâtiments
-Nombre d'étage
-Année de construction

**Comment by iamkinetic** [comment]
L'alignement à droite pour une colonne qui contient des valeurs numériques et à gauche pour des colonnes de texte est pas mal un standard informatique.  Excel a exactement le même comportement.

**Au programmeur** : on pourrait mettre l'éditeur nécessaire à cette colonne pour éviter de bust le nombre maximal de chiffre d'un entier et l'entrée de caractères qui ne sont pas des entiers valides pour éviter l'erreur du filtre.

**Comment by alexandrelabbe** [comment]
10-4 pour l'alignement

Cellule "Terrain vacant", cette cellule est centrée est-ce 0k ainsi?
