### ISSUE TITLE
Statistiques - Fichier PDF

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#319]
Quand on sélectionne "PDF fichier" dans l'outils de statistiques, le rapport généré affiche une erreur quand on essaie de le consulter.

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/726015fe-9ec4-4ccc-b879-45b6a6d9af18)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/d1b77fab-574f-4513-a31b-861adc4a3796)

**Comment by iamkinetic** [comment]
La page des statistiques est complètement fake.  Elle a été fait rapidement pour le démo de l'ACSIQ et les données qu'elle affiche sont fictives.

**Comment by jocelyncardinal** [comment]
Issue a être fermé ...

**Comment by iamkinetic** [comment]
@jocelyncardinal Veux-tu qu'on désactive la page en attendant qu'elle soit faite?

**Comment by jocelyncardinal** [comment]
Non, laisse-la stp elle est utile pour démo ...

Le 24 oct. 2018 à 09:02, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jocelyncardinal<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7C5b3aac1c49cb48533b2108d639b0ea83%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636759829337760632&sdata=aJg4PrI5djXuWpgwx9viiZONR8Q1nc3BYhLL7Fi6QI0%3D&reserved=0> Veux-tu qu'on désactive la page en attendant qu'elle soit faite?
