### ISSUE TITLE
Faire le tour des drop downs pour que l'ordre par défaut soit logique et s'assurer que la recherche fonctionne.

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#320]
1 - Quand on clique sur le menu déroullant, serait-il possible de faire apparaître les SSI en order numérique?

2 - Quand on entre du texte dans la cellule de recherche, serait-il possible que "(tous)" soit surligné et qu'il soit automatiquement "écrasé" par la nouvelle entrée?

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/8055e26c-d9ed-4a8a-9e9d-0c64a98deec8)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/af7be45c-4e0d-4fd2-84d1-b49bdb99f4b0)

**Comment by iamkinetic** [comment]
Faire le tour des listes du même genre.

**Comment by iamkinetic** [comment]
Attention, deux drop downs.

**Comment by alexandrelabbe** [comment]
> @alexandrelabbe On ne corrigera pas le "(tous)" qui ne se clear pas tout seul parce qu'on ne semble pas pouvoir le faire.

10-4
