### ISSUE TITLE
Gestion du SSI - Niveaux de risque par SSI - Cellule Niveau de risque

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#325]
Bugs trouvés : 
1 - On peut entrer des chiffres, lettres, ponctuations et symboles dans cette cellule

2 - Si on entre seulement une lettre dans la cellule de recherche (EX: f), ou un mot entier (Ex: "Faible") aucune réponse n'est retournée / affichée

Bugs corrigés : 
1 - Permettre la recherche par niveau de risque dans la grille.

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/99c72e4e-0c09-4dc4-a735-5d44b19f7912)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/6eb3d144-5890-47b6-a023-6c9c0c5f935b)

**Comment by iamkinetic** [comment]
Mettre la recherche en mode texte plutot qu'avec les drop downs.

**Comment by iamkinetic** [comment]
"calculateFilterExpression"

**Comment by iamkinetic** [comment]
+ #332
