### ISSUE TITLE
Tableau de bord - Bâtiment - Création Lot

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#326]
Je sélectionne des bâtiments, je clique sur "Créer un lot", j'entre un nom "Test Alex Creation Lot", je clique sur Annuler.  Le lot est tou de même créé

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/2405b994-be64-4b80-a9df-28f8cc8f7ca3)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/064ba729-0110-45d2-853a-7fe9fb2d1d1b)

**Comment by iamkinetic** [comment]
Le lot est créé aussitôt que tu entres le nom.  Quand la fenêtre du lot s’ouvre, le lot est déjà créé.  Le bouton annuler sert à annuler les changements depuis que la fenêtre est ouverte.  Ce qui peut être trompeur, c’est que le bouton annuler est disponible même s’il n’y a pas eu de changement.

**Comment by iamkinetic** [comment]
@jocelyncardinal Vu que ça fait deux ou trois fois que ce point sort, que dirais-tu si on ajoutait un bouton "Supprimer le lot" dans la fenêtre du lot?

Sinon, on pourrait simplement désactivé "annuler" quand on a pas de modification en cours pour le lot.

**Comment by iamkinetic** [comment]
Nous n'avons finalement pas mis de bouton "Supprimer le lot" parce que ça nous paraissait pas logique.  Mais le bouton "annuler" ne sera plus disponible lorsqu'il n'y a rien à annuler.

**Comment by jocelyncardinal** [comment]
Oui et de toute façon on a la poubelle pour supprimer le lot dans le tableau de bord
