### ISSUE TITLE
Gestion des SSI - Niveaux de risques

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#332]
1 - On peut entrer des caractères autres que alphabétiques dans cette cellulaire, serait-il possible d'y entrer seulement des lettres?

2 - Si on entre une lettre ou un niveau de risque, aucune valeur ne nous est retournées

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47384996-d7670b00-d6d6-11e8-82ab-67c1bcd3aabe.png)

![image](https://user-images.githubusercontent.com/44094567/47385001-db932880-d6d6-11e8-8a29-1d7285f0a9df.png)

**Comment by iamkinetic** [comment]
Enlever le filtre

**Comment by iamkinetic** [comment]
Fait via #325
