### ISSUE TITLE
Tri les # civiques ordre numérique plutôt que alphanumérique

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#336]
![Capture d’écran 2018-10-24 à 10.02.11.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/6d460833-a57b-4f4c-aa3c-19a082a8510e)

**Comment by iamkinetic** [comment]
Déjà corrigé, voir #299.
