### ISSUE TITLE
Question - Recherche des voies de circulation, on peut sélectionner « (tous) » et par la suite, il y a une ligne « vide » ? 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#337]
![Capture d’écran 2018-10-24 à 10.04.37.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/da53eb41-6b38-405c-9153-f58ccae1d41c)

**Comment by iamkinetic** [comment]
C'est littéralement une rue qui n'a pas de nom.  Elle existe telle quelle dans la RAO, je n'ai pas investigué plus loin.

**Comment by jocelyncardinal** [comment]
On peux vivre avec ca ... pas de crash associé
