### ISSUE TITLE
Question - Devrions-nous permettre de sélectionner plus qu’une ville à la fois?

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#338]
![Capture d’écran 2018-10-24 à 10.06.05.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ee5dcbde-d1cc-43dd-ab37-85a66c188b7d)

**Comment by iamkinetic** [comment]
@jocelyncardinal À quel endroit dans le site web?

**Comment by jocelyncardinal** [comment]
Dans la recherche sur une colonne ... c'est seulement une question d'Alexandre et selon moi ce n'est pas une fonctionnalité qui me semble essentiel (plus un nice to have). Donc,  si tu es d'accord la réponse serait "non" et on ferme l'issue 

![capture d ecran 2018-10-24 a 11 24 33](https://user-images.githubusercontent.com/32175949/47441991-7ba48c80-d77f-11e8-8aad-6eae9193d029.png)

**Comment by iamkinetic** [comment]
D'accord!
