### ISSUE TITLE
Observation - Les nouveau champs telle « Code postal » seront initialement vide (absent du logiciel CAUCA)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#339]
![Capture d’écran 2018-10-24 à 10.09.45.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/d58c9c88-2603-4b7a-baf2-beb00b94802d)

**Comment by iamkinetic** [comment]
Je peux te confirmer qu'une grande partie des bâtiments de SURVI-RAO contiennent un code postal.   Possiblement que ces bâtiments sont importés d'un autre système (Première Ligne ou autres).

SURVI-Prévention est un logiciel qui ne dépend pas d'un autre système, donc qu'un autre système gère ou pas le code postal n'a pas d'importance pour nous.

**Comment by jocelyncardinal** [comment]
D'accord! Donc, on peux fermer l'issue/question
