### ISSUE TITLE
Question - On fait quoi avec la colonne « Lot » ?

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#340]
![Capture d’écran 2018-10-24 à 10.13.11.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/29f9bd42-a896-4d85-b2fa-9e20f5d31ba1)

**Comment by jocelyncardinal** [comment]
![Capture d’écran 2018-10-24 à 10.13.22.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fd79e957-a4b5-4169-88aa-2f1251535202)

**Comment by iamkinetic** [comment]
Voir si on pourrait enlever "# Lot" des colonnes disponibles à la customization.  Il doit y avoir une option pour ça.  En réalité, le lot est déjà affiché quand il peut l'être (via le regroupement).

**Comment by jocelyncardinal** [comment]
Exactement donc ça ne sert à rien d’avoir cette colonne … sauf peut-être pour les inspections complétées ?

**Comment by iamkinetic** [comment]
Fixed via #318.
