### ISSUE TITLE
Observation - Alignement des cellules a valider

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#342]
![Capture d’écran 2018-10-24 à 10.44.34.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7144faa4-fdec-4807-b0da-7bf91da836e2)

**Comment by iamkinetic** [comment]
C'est un standard.  C'est exactement comme dans Excel, les colonnes "numériques" par défaut sont alignées à droite, les colonnes "textes" à gauche, etc.

**Comment by iamkinetic** [comment]
À moins d'avis contraire, nous garderons le comportement par défaut.

**Comment by jocelyncardinal** [comment]
Parfait!
