### ISSUE TITLE
Colonne « Générer le rapport » devrait être disponible que dans le mode "Inspection complétée".

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#343]
![Capture d’écran 2018-10-24 à 10.45.29.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/196a6f55-fb29-49b6-8a4f-9de7ea380d8a)

**Comment by jocelyncardinal** [comment]
Idéalement, devrait être par défaut comme colonne dans l'onglet "inspections complétés" et ne devrait donc pas être disponible dans la choix des colonnes. Notez que c'est un issue "low priority" a faire si c'est facile a implémenter. Sinon, c'est pas la fin du monde non plus, on a juste a ne pas l'ajouter/l'enlever. Je pense que les usagers peuvent très bien vivre avec ca.

![Capture d’écran 2018-10-24 à 10.49.33.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/45c4a3e9-9dc4-4878-b0b3-9b933238ce0e)

**Comment by iamkinetic** [comment]
Voir ce qu'on peut faire et qui ne prendra pas des heures.

**Comment by iamkinetic** [comment]
Fixed via #318.
