### ISSUE TITLE
Les images ne s'imprime pas dans le rapport

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#345]
Exemple d'utilisation de  @BuildingAnomalyPicture.PictureData@ pour imprimer l'image dans le rapport?

![Unknown.jpeg](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/bad553f2-15b9-44b7-8adb-88273883c506)

Voici le résultat ...

![Unknown-1.jpeg](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4626a711-2381-43b7-b469-887923079b0e)

**Comment by iamkinetic** [comment]
Déjà corrigé pour nous, fix dans la prochaine version.  Voir : CAUCA-9-1-1/survip-webapi#155

**Comment by jocelyncardinal** [comment]
ok super!  prochaine version sera en ligne vendredi ?
