### ISSUE TITLE
Menu n'apparait plus dans l'app mobile selon le niveau de risque par SSI (multiselect)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#348]
Aucun menu ???

![IMG_0565.jpg](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/c8470478-58e9-4876-8bac-b0c768f9572a)

Probablement relié au dernier changement fait dans niveau de risque par SSI (multi-selection)

![Capture d’écran 2018-10-24 à 15.41.55.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/dc01a8a9-c56c-41c3-9472-a40d370ea115)

**Comment by iamkinetic** [comment]
@jocelyncardinal La plupart des items du menu ne sont pas disponibles tant que l'inspection n'est pas commencée et cette inspection n'est pas commencée.  C'est ce qui explique sans aucun doute ce problème.

**Comment by jocelyncardinal** [comment]
D’accord, merci beaucoup pour le retour rapide. J’ai testé et ça fonctionne.  Issue à fermer
