### ISSUE TITLE
Risques Particuliers

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#357]
1 - Si on doit prendre une photo, un message "bilingue" nous est affiché en version française

2 - Une fois la photo prise, on nous offre "Retake" ou "Use Photo" en version française

3 - Si on consulte une photo, le bouton "Back" est affiché dans la version française

4 - Fondation, Plancher, Toit, Section "Localisation" - On nous offre de localiser le risque particulier de la fondation sur un mur, est-ce 0k ainsi?

4 - Si on veut éditer une photo, qu'on doit "déplacer l'image" et qu'on veule y avoir une note, le bouton pour déplacer l'image demeure sélectionner, on doit déselctionner manuellement le bouton afin de pouvoir faire nos modifications.  est-ce 0k ainsi?  (via CAUCA-9-1-1/survip#296)

5 - Section "Commentaires" - Combien de caractère peut-on entrer? Devrions nous faire apparaitre un "compteur de caractères" et une barre de défilement si besoin il y a?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47575247-a3c2f580-d90f-11e8-8123-d3e036b9a67b.png)

![image](https://user-images.githubusercontent.com/44094567/47575269-b3423e80-d90f-11e8-8a53-e07d1124019b.png)

![image](https://user-images.githubusercontent.com/44094567/47575401-03210580-d910-11e8-87e5-56cd15b5fd47.png)

![image](https://user-images.githubusercontent.com/44094567/47575460-26e44b80-d910-11e8-95ae-9b33d4f3b0d2.png)

![image](https://user-images.githubusercontent.com/44094567/47575560-601cbb80-d910-11e8-9d36-7a5dd67422ab.png)

![image](https://user-images.githubusercontent.com/44094567/47575617-85112e80-d910-11e8-8433-82609a0ff357.png)

**Comment by iamkinetic** [comment]
Attention de créer les points dans la bonne application.

**Comment by alexandrelabbe** [comment]
Veux-tu que je ferme ce ticket et que je le créé à nouveau dans l'onglet "mobile"?

**Comment by iamkinetic** [comment]
@alexandrelabbe Tous les points qui ont rapport à la fenêtre d'édition des photos (sketch tool) ont pas mal déjà été trouvé, dont celui qu'on peut avoir deux boutons sélectionnés en même temps.  

Cet outil est développé par Audrey qui est la stagiaire de Jocelyn.  Elle va donc s'occuper de régler ces petits accrocs dans des points créés à part.

**Comment by iamkinetic** [comment]
@alexandrelabbe

On ne mettra pas de compteur de caractère et la limite du nombre de caractère est tellement élevé que tu pourrais écrire un livre au complet.  Il y a une barre de défilement, mais semble apparaître que lorsqu'on "scroll" seulement.

De pouvoir localiser la fondation sur un mur était dans la demande.  La seule différence entre les 4 types de risque selon la demande initiale est que la fondation a la dimension du bâtiment et pas les autres.

**Comment by iamkinetic** [comment]
Les points à faire sont donc ceux-ci:
* Traduction dans la prise et sélection de photo
* Améliorer l'édition de commentaire.

**Comment by iamkinetic** [comment]
@alexandrelabbe Apparemment que de ne pas avoir la scrollbar visible est le comportement voulu sur les appareils mobiles.  J'ai réussi à faire afficher cette scrollbar en tout temps sur Android et pendant qu'on scroll sur iOS, mais il ne semble pas y avoir de façon d'aller plus loin.  J'ai aussi mis le commentaire sur 10 lignes ce qui fera qu'on aura pas besoin du scroll bar avant d'entrer pas mal de texte.

J'ai aussi réussi à faire marcher la traduction dans la fenêtre de prise de photo, mais les petits bouts de texte qui s'affiche quand ça nous demande la permission d'accéder à la caméra ne semble pas être "traduisible".
