### ISSUE TITLE
Questionnaire - Ajouter la capacité de dupliquer un questionnaire

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#361]
Il serait très pratique de pouvoir de dupliquer un questionnaire. Refaire un questionnaire au complet prend du temps et le risque d'erreur est élevé. Aussi une fonction permettant de dupliquer faciliterait la création d'un nouveau questionnaire a partir d'un autre déjà fait (et testé). Notez que la plupart des questionnaires risquent d'être très similaire avec quelques variations. Par exemple, un simple bouton dupliquer entre la poubelle et le crayon ferait l'affaire ... on clique dessus et on obtient un nouveau questionnaire avec "(copie)" dans la nom qu'on pourra modifier ensuite ...

![Capture d’écran 2018-10-26 à 16.42.35.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/be9e709e-67b9-4117-b324-31542ef330a6)

**Comment by iamkinetic** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/related-data#including-multiple-levels
