### ISSUE TITLE
Liste des bornes incendie

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip#363]
1 - Nous avons le bouton "Back" affiché en haut à gauche, pourrions-nous le renommer par "Retour" ou qqch comme ça?

2 - Dans la barre de recherche s'affiche "Search", pourrait-on modifier par "Recherche"?

3 - Si je clique sur "Ajouter.." que je clique sur la borne # 345, la borne se créée à nouveau, est disponible 2 fois

4 - Si on clique sur "Détails de la borne", le bouton "Back" est affiché, serait-il possible de renommer par "Retour"

5 - "Créer nouvelle borne" - La fenêtre semble ne pas se "recadrer".  Dans la section "Pression", j'ai cliqué sur "À" et le curseur pour entrer un valeur affiche "au travers" de la barre "Annuler"

6 - "Créer nouvelle borne" - Débit et Pression, on peut entre des chiffres, lettres, ponctuations et symboles dans les boite texte. Pourrait-on vérouiller pour du numérique seulement?
     Combien de caractères peut-on entrer dans ces cellules?  Devrait-on les "geler" à 3 ou 4?

7 - "Créer nouvelle borne" - "Localisation" - "Voie" 
     Premiere fois que je clique sur "voie" pour sélectionne une rue, rien ne s'est affiché. Je clique sur "Recherche" et l'application cherche pendant plus d'une minute avant de "planter"  M' rammené à l'écran d'accueil, j'ai dû entrer mes informations à nouveau
     Outil de recherche, si on entre un "/", un message d'erreur nous est retourné

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47659877-42e42900-db6c-11e8-8f4d-5f92af1c7818.png)

![image](https://user-images.githubusercontent.com/44094567/47659896-4b3c6400-db6c-11e8-892a-25c9673baca9.png)

![image](https://user-images.githubusercontent.com/44094567/47659934-5e4f3400-db6c-11e8-9095-1661cfa11c0f.png)

![image](https://user-images.githubusercontent.com/44094567/47659974-70c96d80-db6c-11e8-8011-c148e82a7c38.png)

![image](https://user-images.githubusercontent.com/44094567/47660107-b6863600-db6c-11e8-8f95-4e34337b439a.png)

![image](https://user-images.githubusercontent.com/44094567/47660172-d6b5f500-db6c-11e8-93fd-868e348675b0.png)

![image](https://user-images.githubusercontent.com/44094567/47660240-0238df80-db6d-11e8-95ac-dec6cc84fde5.png)

**Comment by iamkinetic** [comment]
Seront corrigés via CAUCA-9-1-1/survip-mobile#263
