### ISSUE TITLE
Le refresh Token de la page web ne semble plus fonctionner

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#365]
Après un certain moment le token de l'utilisateur de la page web expire malgrès une mutlitude requeêtes envoyées.
Il faudrait valider que le refresh token d'un usager fonctionne lorsque celui-ci fait une requête ou dès que celui-ci arrive à terme.

Ce point peut entrianer des modifications dans l'API.

**Comment by iamkinetic** [comment]
Je dirais qu'il est fort peu probable que le problème soit dans l'API.  À mon avis, la fonctionnalité n'a juste jamais bien marché.
