### ISSUE TITLE
Nom du lot apparait pas quand on utilise "Masquer tout"

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#369]
![Capture d’écran 2018-10-30 à 17.29.40.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/bacf0bfa-8088-404b-af13-2d2d7a39c0a3)

**Comment by iamkinetic** [comment]
* Le nom du lot n’apparaît plus dans le groupe quand il est réduit.
