### ISSUE TITLE
Lot d'inspection - Suppression d'un Lot fait disparaitre les inspections approuvées (bug)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#370]
Une inspection assigné au lot X a été complétés et approuvés ...

![Capture d’écran 2018-10-30 à 17.37.57.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/11a5bf6b-026c-4e23-bd20-697c46b905bf)

On supprime le lot X ...

![Capture d’écran 2018-10-30 à 17.38.10.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a12b620a-a566-40b5-95e7-6f7629c5b719)

...l'inspections approuvées est disparue...

![Capture d’écran 2018-10-30 à 17.39.15.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/9197a675-62f1-4b25-9228-511a361c99c8)

**Comment by iamkinetic** [comment]
* Ne pas permettre de supprimer un lot qui contient des inspections terminées ou en attente d'approbation.

**Comment by iamkinetic** [comment]
Sera fait via #375.

**Comment by philipperobertgh** [comment]
Modifications à faire:
 - Ajout du statut de l'inspection dans le popup d'édition du lot
 - Validation avec message sur suppression d'inspection dans le popup d'édition du lot si celle-ci est à un autre statut que "À faire".
 - Validation avec message sur suppression de lot dans le tableau de bord des lots à faire si une des inspections de ce lot est à un autre statut que "À faire".

**Comment by iamkinetic** [comment]
Et ne carrément pas donner la possibilité de supprimer une inspection terminée.

**Comment by iamkinetic** [comment]
https://www.devexpress.com/Support/Center/Question/Details/T483255/dxdatagrid-how-to-hide-the-edit-delete-links-buttons-for-specific-rows
