### ISSUE TITLE
Lot d'inspection - Lors de l'assignation, le choix des inspecteur devrait être limité au le SSI

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#371]
Présentement tous les usagers sont disponible dans le dialog box ...

![Capture d’écran 2018-10-30 à 18.43.54.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/711f5200-b736-47cf-bbf6-9bab2b2f2a76)

Lors de l'assignation, le choix des inspecteur devrait être limité au le SSI telle que configurer par usager ...

![Capture d’écran 2018-10-30 à 18.44.56.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/685acaf2-0dfa-4b1c-9514-5c31fb487895)

**Comment by iamkinetic** [comment]
@jocelyncardinal Tu veux dire limité aux usagers des SSIs auxquels le configurateur à accès?

Parce qu'un lot pourrait contenir des bâtiments de plus d'un SSI.

**Comment by jocelyncardinal** [comment]
Oui, c'est ca ... limité aux usagers (inspecteurs) des SSIs spécifiés dans la configuration de l'usager (celui qui assigne les inspection). Note qu'il pourrait avoir plusieurs SSI comme l'exemple suivant ...

![capture d ecran 2018-11-02 a 11 31 23](https://user-images.githubusercontent.com/32175949/47924950-5c9aae80-de93-11e8-8fed-2078fa58e181.png)

**Comment by iamkinetic** [comment]
Will be fixed via #375.
