### ISSUE TITLE
Toutes les colonnes deviennent sélectionné 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#376]
Toutes les colonnes ont été sélectionné sans que le le demande (suite a la création lot lot lot test issue#359a (usager/ password = patrick.giguere/ereugig1234) voir issue 359

![Capture d’écran 2018-11-02 à 11.53.35.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/6dd17244-ec38-4ba6-85a1-6d05b2838b36)

**Comment by jocelyncardinal** [comment]
Ok, je pense que j'ai compris ... c'Est simplement un autre usagers qui a du modifier les colonnes sur son usagers et cela a affecté le mien - voir issue #377 ...

**Comment by iamkinetic** [comment]
Je vais fermer le point.  Si ça arrive encore, vous en créerez un nouveau.

À garder en tête que la configuration est par ordinateur et non par utilisateur.

**Comment by jocelyncardinal** [comment]
D'accord!
