### ISSUE TITLE
Configuration des colonnes devrait être spécifique par usagers

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#377]
Présentement, les choix de colonnes sont générale pour tous les usagers ... si change le choix de colonnes a afficher, ce chois se répercutera aussi pour les autres usagers ...

![Capture d’écran 2018-11-02 à 16.33.05.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ab2e7a91-4590-48f0-8908-18ba18aebe45)

![Unknown.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/b8b44bed-314e-4d54-89e7-92114e4805b0)

**Comment by iamkinetic** [comment]
La sauvegarde des colonnes est "par browser".  Donc si tu utilises plusieurs usagers sur le même ordinateur, ils auront tous la même configuration.

**Comment by jocelyncardinal** [comment]
Ok, ça fait du sens! La configuration des colonnes est très relié à l’ordinateur (browser) utilisé (screen résolution).

Toutefois, ça invalide ma théorie par rapport a la problématique survenu lors de ma création des lots de test - toutes les colonnes sont soudainement devenues sélectionnées ??? Note qu’on peut considérer Low priority pour l’instant... j’ai juste eu à resetter les colonnes en 5 secondes ... on verra si ça reviens
