### ISSUE TITLE
Rapport - Feedback visuel "en attente" durant de la génération du rapport

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#380]
Durant le génération du rapport, il faudrait donner un feedback visuel que le système est en  "processus" - Par exemple, un icone  en attente durant de la génération du rapport

![Capture d’écran 2018-11-06 à 10.10.24.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/10291916-f389-45a7-8d9f-00798894517c)

Idéalement un icône animé (animated GIF???) durant les quelques secondes que prend le serveur pour pour générer le rapport en format PDF  ...

![Capture d’écran 2018-11-06 à 10.05.49.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/807267a8-0bd1-4170-a4ac-398f1a85952d)

**Comment by jocelyncardinal** [comment]
Commentaire - Il faudrait aussi penser a la possibilité de faire des générations de rapports en "batch" via la multi-sélection. Toutefois, je mettrais ca "low priority" pour l'instant et de garder ca en tete dans l'élaboration de la solution "finale" de la génération du rapport.

**Comment by iamkinetic** [comment]
* Il y a déjà un point pour les rapports en batch: #243

**Comment by iamkinetic** [comment]
Nous utilisons DevExtreme dans le site web, donc on peut utiliser son LoadPanel pour faire ça question de rester uniforme dans le style :

https://js.devexpress.com/Documentation/Guide/Widgets/LoadPanel/Overview/
