### ISSUE TITLE
Report - Réponse a développement affiche parfois un ID au lieu du contenu

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#388]
![Capture d’écran 2018-11-07 à 16.43.41.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/e071f799-5155-43be-b01f-a1fd5de52e91)

![Capture d’écran 2018-11-07 à 16.48.03.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/136a4959-4e7a-40fe-aea3-d2ef82f38227)

![Capture d’écran 2018-11-07 à 16.50.09.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ce591aca-5ad2-4639-aba1-3d4124447e78)

**Comment by jocelyncardinal** [comment]
Note que la plupart du temps ca fonctionne bien ...

![Capture d’écran 2018-11-07 à 16.58.54.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7b4e0f23-4c38-4b89-a11e-023bba0ff5d4)

**Comment by iamkinetic** [comment]
Est-ce que ça le fait dans une inspection en particulier?

**Comment by iamkinetic** [comment]
@jocelyncardinal

Ok, je peux voir le bug avec la même inspection qui causait le trouble de répétition.

Techniquement, ce qu'affiche le rapport est correct:  la question est de type "développement", mais le texte de la réponse est l'id d'un choix d'une autre réponse.

Alors je me pose deux questions :
* Est-ce que le questionnaire a été modifié après qu'il ait été répondu pour l'inspection?
* Est-ce qu'il y a un bug dans le mobile qui ferait que les réponses ne vont pas toujours dans la bonne question?

**Comment by jocelyncardinal** [comment]
*   Est-ce que le questionnaire a été modifié après qu'il ait été répondu pour l'inspection? Réponse: non

  *   Est-ce qu'il y a un bug dans le mobile qui ferait que les réponses ne vont pas toujours dans la bonne question? Réponse : peut être mais je n’avais pas remarqué de symptômes en ce sens

**Comment by iamkinetic** [comment]
Clairement le bug n'est pas dans le rapport parce qu'il affiche ce qu'il doit afficher.  J'ai créé un point pour l'application mobile : CAUCA-9-1-1/survip-mobile#269
