### ISSUE TITLE
Rapport - Répétition des 4 premieres sections du rapport (2 fois) dans le PDF

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#389]
Génerer rapport 400 rue raymond ...

![Capture d’écran 2018-11-08 à 08.40.33.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cb4c3a55-ce20-479f-af37-57863bb67bd1)

1 ere page ok ...

![Capture d’écran 2018-11-08 à 08.43.24.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/b5dba46f-bf1e-429f-a75a-7e762b7ca8cc)

2e et 3e page (BUG) : Répétition des 4 premieres sections du rapport (2 fois) 

![Capture d’écran 2018-11-08 à 08.43.31.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4e5c4d5c-0b81-4d8d-8f89-9728b88092ef)

**Comment by jocelyncardinal** [comment]
[https://app.zenhub.com/files/88898448/d7a95fef-7fd5-4f87-b2d2-930cec10b3ed/download](https://app.zenhub.com/files/88898448/d7a95fef-7fd5-4f87-b2d2-930cec10b3ed/download)

Note qu'il y a deux batiments enfants dans cette inspection ... C'est peux etre relié car les sections se répète 2 fois ... peut-etre relié?

**Comment by iamkinetic** [comment]
Vérifions d'abord la configuration du rapport lui-même.

**Comment by iamkinetic** [comment]
@jocelyncardinal  C'est quel rapport ça exactement?

**Comment by iamkinetic** [comment]
Réponse à moi-même: "Rapport No1".

Cas reproduit.

Toutes les sections du rapport sont fait pour être "répétable".  Si on affiche les risques particuliers et que la requête remonte 3 risques particuliers, la section sera répétée 3 fois.

À mon avis, c'est le problème qu'on dans ce cas-ci.  La requête de la section "Inspection" ou "MainBuilding" remonte incorrectement plus d'un enregistrement.

À vérifier.

**Comment by iamkinetic** [comment]
Problème trouvé.  On utilise la même fonction pour loader les données dans la section [MainBuilding] que dans [Building] sauf qu'il y a un paramètre qui sert à indiquer qu'on veut les enfants ou non.  Dans le call de MainBuilding, on indiquait incorrectement qu'on voulait les enfants.
