### ISSUE TITLE
Page Statistique - Premiere version de base

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#404]
Résultats des visites de prévention
Les mockup sont basé sur l'utilisation des statistic sur survi-prototype (Alain Grégoire, fichier excel)

**Comment by iamkinetic** [comment]
@AudreyLR @JocelynCardinal 

Est-ce qu'on pourrait indiquer le détail de ce qu'il y a à faire exactement?

Est-ce que 5 heures est réaliste? Je ne connais pas l'expérience d'Audrey avec les composantes de statistiques de DevExtreme (et j'en ai moi même pas la moindre), mais ça me parait très peu.
