### ISSUE TITLE
Report generation doesn't work from template "Test Rapport" 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#406]
**Describe the bug**

Report generation doesn't work properly from template "Test Rapport" as it works for other template (Report No1). 

**To Reproduce**

 Generate report using the template "test report"

**Expected behavior**

Print data into the PDF

**Screenshots**

Here the result using "Test Rapport" ...

![Capture d’écran 2018-11-29 à 11.32.01.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5f328f96-0c1f-46eb-9c9a-4a2977d87d97)

Is there any mistake in the template ? 

![Capture d’écran 2018-11-29 à 11.31.22.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/0a346f41-f16e-43b1-9f83-681d28f6ec96)

Here another template that work better "Rapport No1" ...

![Capture d’écran 2018-11-29 à 11.33.37.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/81664b35-359a-4189-9e0e-da6192cea97f)

the template ...

![Capture d’écran 2018-11-29 à 11.30.55.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/82dd0fde-fa2c-4a1b-ab91-9d1a5f1784ad)

**Comment by iamkinetic** [comment]
@JocelynCardinal Il manque la balise de fin: `[/MainBuilding]`. Je l'ai ajouté à ton rapport pour le tester.
