### ISSUE TITLE
Rendre la géolocalisation disponible en tout temps.

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#415]
Il faut enlever le mode "Geolocalisation" des types d'adresse possible pour une borne.  La géolocalisation deviendra disponible en tout temps.

Il ne faut pas oublier d'enlever le code qui réinitialise la coordonnée quand on change de type d'adresse.`

On pourrait en profiter pour changer la fenêtre pour que le popup ne s'affiche que sur demande, comme sur le mobile.

S'assurer que les transversales soient nommées ainsi et non "intersection".

**Comment by philipperobertgh** [comment]
La fenêtre reste trop longue à ouvrir a cause de l'affichage dynamique des controles de localisation.

**Comment by iamkinetic** [comment]
Attendre que #423 soit merged avant de faire celui-ci.

**Comment by iamkinetic** [comment]
#281 doit être fait.
