### ISSUE TITLE
Configuration des rapport - Il faut faire un REFRESH pour voir les rapports 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#425]
**Describe the bug**
Il faut faire un REFRESH pour voir les rapports 

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/2a1ce606-7289-49e5-ba96-78bf231895c9)
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/76ffcef3-40b3-4100-879b-32217a513c60)

**Comment by iamkinetic** [comment]
À mon avis, c'est nous qui avons causé ce problème en corrigeant le problème des menus qui se dupliquaient.

Le tout premier rapport qu'on ouvre fonctionne parfaitement, c'est tous les autres qui suivent qui ne marchent pas.

**Comment by iamkinetic** [comment]
@AudreyLR Si tu trouves pas ce qui cause le problème, on mettra le point "blocked" pour passer à d'autre chose et on y reviendra plus tard, d'accord?

De toute façon on ne fera pas de mise à jour avant une semaine ou deux.

**Comment by AudreyLR** [comment]
@iamkinetic bloqué tant que le pull-request et le publish sur npm de la librairie ne sont pas fait. Je n'ai pas les accès pour le faire, mais il ne resque qu'à update la version dans le branche de survip et ce sera complet.

**Comment by iamkinetic** [comment]
D'accord.  Je vais essayer de te trouver les informations ou de faire moi même le publish de la nouvelle version.
