### ISSUE TITLE
Configuration des rapport - Distinguer rapports par SSI (colonnes SSI)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#426]
**Is your feature request related to a problem? Please describe.**
Les rapports sont spécifiques par SSI avec leurs propres logos et format. Il doivent etre visible seulement par eux. 

**Describe the solution you'd like**
 il faut ajouter une colonne SSI dans le tableau ...
![Capture d’écran 2018-12-13 à 11.29.40.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4219e82e-dbcf-44d5-8220-54aa734f9291)

**Comment by iamkinetic** [comment]
Voir #420 pour la colonne.

Pour le logo, on va le rendre disponible, mais il sera importé avec le SSI.
