### ISSUE TITLE
Make edition validations great again

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#446]
* City management:
  * Limit "code 3 letters" to 3 letters.
  * Limit "code" to 10 characters (or whatever its max length is).
* Region management:
  * Limit code to its max length.
* Province management:
  * Limit code to its max length.
* Country management:
  * Limit fields to their max length.

**Comment by iamkinetic** [comment]
@Jeepsboucher Voici une partie de tes points

**Comment by Jeepsboucher** [comment]
* Risk level:
  * Limit code to its max length.
