### ISSUE TITLE
Gestion des bornes - mettre la géolocalisation dans un vrai popup

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#455]
Loader la carte seulement quand on clique sur l'icone de géolocalisation.

**Comment by philipperobertgh** [comment]
Ce n'est pas le chargement de la cartographie qui ralentit l'ouverture de la page mais la procédure d'affichage des contrôles selon le type de localisation.
Donc ce point n'est plus nécessaire
