### ISSUE TITLE
Rendre la raison sociale accessible à la consultation et l'édition

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#456]
* [ ] Ajouter la raison sociale dans la table de bâtiment (non localized).
* [ ] Ajouter la raison sociale dans le DTO et l'importation/exportation.

Pour ces trois points, attendre que #301 soit merged.
* [ ] Afficher la raison sociale dans la page d'informations générales.
* [ ] Permettre l'édition de la raison sociale dans "détail du bâtiment".
* [ ] Permettre l'édition de l'alias du bâtiment dans "détail du bâtiment".

**Comment by iamkinetic** [comment]
Note à nous : le champ semble être nomSubdivision meme si ce n'est pas une subdivision.

**Comment by jocelyncardinal** [comment]
@jocelyncardinal<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7C55826e8d2e7e41eea80708d68bb0b2b6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636849988353679113&sdata=l1sgjtNjfmzmgCXEgYXUTyYeVH9Y889cW3CcSAl5SRA%3D&reserved=0> Est-ce qu'on veut l'alias du bâtiment ET la raison sociale ou seulement la raison sociale?

Réponse :

Idéalement, on voudrait l’alias du bâtiment ET la raison sociale.  L’alias c’est un peu comme un synonyme. Ex. : Raison sociale : Centre d’achat Galeries des Cantons. Alias : IGA, Jean Coutu, Banque Nationale. Dans ce cas-ci les alias font partis du bâtiment principal qui est le centre d’achat. Donc oui ça prend les deux.

**Comment by iamkinetic** [comment]
J'ai splitté ça en deux points : un pour SURVI-Prévention Web et un pour SURVI-Prévention Mobile.  C'est la raison pour laquelle je ferme celui-ci.
