### ISSUE TITLE
Reporting - Image does not print in report

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#463]
**Describe the bug**
Image does not print in report

**Screenshots**
Design mode ...
![Capture d’écran 2019-02-07 à 12.37.04.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/1a931cf7-5852-40a7-89fb-1009b312f5a8)

Result into PDF
![Capture d’écran 2019-02-07 à 12.37.36.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/033b0857-35ba-45b1-bfc7-5cbbcca25ee9)

**Comment by jocelyncardinal** [comment]
1. Audrey to test for Plan d'implantation, anomalies, risque particulier
2. Check if sketch is well added to the image

**Comment by iamkinetic** [comment]
Pour une raison ou une autre, la variable "PictureData" dans les anomalies et les risques particuliers a été renommée pour "DataUri", mais une partie du code n'a pas suivi.

Je suis en train de corriger ça via #364.
