### ISSUE TITLE
Reporting - Default check box reset when saving modification

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#464]
**Describe the bug**
Reporting - Default check box reset when saving modification

**Screenshots**
![Capture d’écran 2019-02-20 à 14.36.53.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ea6fc10d-b4fc-48fe-9af2-5cc66f286b02)

**Comment by iamkinetic** [comment]
Fixed via cauca-9-1-1/survip#264
