### ISSUE TITLE
Update version of angular

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#465]
Survip doesn't have the latest version available of angular, we must be up to date :
@angular/cdk             6.4.6 -> 7.3.2           ng update @angular/cdk
@angular/cli               6.1.5 -> 7.3.2           ng update @angular/cli
@angular/core            6.1.6 -> 7.2.6           ng update @angular/core
@angular/material      6.4.6 -> 7.3.2           ng update @angular/material
rxjs                               6.2.2 -> 6.4.0           ng update rxjs

Update to the latest version available and check for possible changes to be made

**Comment by iamkinetic** [comment]
Est-ce qu'il y a un gain à faire ça?
