### ISSUE TITLE
No match for "Caserne 6775 Prevert, Saint-Hyacinthe" 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#467]
**Probably not a bug**

No match for "Caserne 6775 Prevert, Saint-Hyacinthe". 

Just validate if the address "6775 Prevert" exist in database. It should because it is actually the adresse of the fire station for the city of Saint-hyacinthe.

**Screenshots**

![Capture d’écran 2019-02-07 à 12.02.33.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/decb5f7f-7bb7-4665-89e6-c5cd687e4d2f)

![Capture d’écran 2019-02-07 à 12.05.57.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/3879ac82-8cf6-4c0a-bfe8-b76b1e06444f)

![Capture d’écran 2019-02-07 à 12.01.56.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/53aa5389-6792-4645-99c0-35ee6ae177d0)

**Comment by iamkinetic** [comment]
@JocelynCardinal 

La caserne est configurée comme étant au "6765, Prévert" dans le logiciel CAUCA.

Ce bâtiment a en réalité un # civique supérieur et inférieur:

"6765-6775, Avenue Prévert"

Nous n'avons pas mis le # civique supérieur dans la requête du tableau de bord.
