### ISSUE TITLE
Ne pas afficher le mot de passe de confirmation lorsqu'on créé un nouveau user

### ISSUE THREAD

**Issue by yjacques940** [CAUCA-9-1-1/survip#478]
- [ ] Faire afficher le mot de passe avec des *

**Comment by iamkinetic** [comment]
Comment tu reproduis ça?  Ça semble déjà afficher des astérisques dans mes tests:
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/9f7e8dc5-2997-4eff-97f4-752d5457a862)

**Comment by yjacques940** [comment]
![pasdetoileconfirmationmdp](https://user-images.githubusercontent.com/40217275/53570706-244f6800-3b35-11e9-8655-09de25beb0a1.PNG)

Je suis en "debug", je ne fait qu'ouvrir la fenêtre pour un nouvel utilisateur et le mdp m'apparait

**Comment by iamkinetic** [comment]
Dans quelle branche tu roules SURVIP?

**Comment by yjacques940** [comment]
webApi: 287
survip: 417

**Comment by iamkinetic** [comment]
@philipperobertgh Es-tu capable de reproduire ce bug de ton côté?
