### ISSUE TITLE
Printout of PDF take only half of the page (785 rue couvent, waterville)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#481]
**Describe the bug**
Sometime the printout of PDF in not properly done. The problem occurs with the inspection "(785 rue couvent, Waterville)" with Patric Giguere as user (pass=ereugig1234)

See the screenshot for details

**Screenshots**
Log ...
![Capture d’écran 2019-02-28 à 16.19.38.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/98ab199b-9940-4e83-9cfe-87dee37f88b0)

Generate PDF...
![Capture d’écran 2019-02-28 à 16.19.14.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/711da9df-4175-429a-9c64-1a28c27c6bec)

Here the result ...
![Capture d’écran 2019-02-28 à 16.18.17.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5475c2a3-d143-403a-ad5e-233252eb930f)

**Comment by jocelyncardinal** [comment]
The problem is probably related to the fact that images does not print in the report. We added two anomalies with images in that report (images don't appear - issue #463). When a remove the section anomalie from the report the print out is OK

![Capture d’écran 2019-02-28 à 16.39.17.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/61d02909-a781-4fe5-8003-fd977c2dcc0b)

**Comment by jocelyncardinal** [comment]
**Additional testing with table containing the image ...**

One table without image (test1) and the other one containing an image (test2) ...

![Capture d’écran 2019-03-04 à 11.01.30.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/007a0574-470a-4a62-a5aa-ed9bdebf3e17)

We see that the problem is related to the fact that the width of the images is huge (even is the image don't print don't appear - issue #463).

![Capture d’écran 2019-03-04 à 11.01.54.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/90887f20-18f9-416c-a46a-26911b1d0bb1)

I renamed the report "... (issue 481)" for convenience ...

![Capture d’écran 2019-03-04 à 11.04.59.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/3f830aff-c57a-4046-aceb-eff51dafd11c)

**Hope it helps :)**

**Comment by iamkinetic** [comment]
À vérifier si ce problème existe encore avec la correction pour les images avant de trop mettre de temps là dessus.

**Comment by iamkinetic** [comment]
@jocelyncardinal est-ce un point qu'on doit garder ouvert ou c'est correct finalement?

**Comment by jocelyncardinal** [comment]
Le problème ne semble plus se reproduire donc je crois qu'on peut fermer ce point
