### ISSUE TITLE
We can add multiple times the same user in a group

### ISSUE THREAD

**Issue by yjacques940** [CAUCA-9-1-1/survip#483]
when we add a user in a permission group, we can add multiples times the same member in it. 
I tried it in Test and local
![multiple_time_same_member.PNG](https://images.zenhubusercontent.com/5c47399b5109305a7c6208f9/18b276a4-904f-4f7d-88b0-1ed95c4aa5aa)

**Comment by philipperobertgh** [comment]
Fonctionnalité choisie:
 - Un usager ne peut-être que dans un seul group de permission
     -> Fait dans #480
