### ISSUE TITLE
A user that doesn't have the "manage permission" permission can't log in to the site

### ISSUE THREAD

**Issue by yjacques940** [CAUCA-9-1-1/survip#485]
Pour recréer le bug: 
-Créer un user
-Lui mettre les permissions de gérer les permissions à NON (le mettre dans un groupe de permissions..)
-Déconnexion
-Se reconnecter

![cannot_connect.PNG](https://images.zenhubusercontent.com/5c47399b5109305a7c6208f9/651a697a-0b93-4749-827c-13ede5bce013)

**Comment by yjacques940** [comment]
Se reconnecter avec le nouveau User***

**Comment by iamkinetic** [comment]
Non répété.

@philipperobertgh Je vais mettre ce point à tester et tu feras le test pour voir si tu réussis à reproduire le problème mentionné par Yannick.

**Comment by philipperobertgh** [comment]
Pas réussi à reproduire.

**Comment by philipperobertgh** [comment]
Corrigé dans le #488
