### ISSUE TITLE
Inspection approval - fire hydrant management

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#494]
In the inspection approval when we check the building firehydrant we have multiple problems:
 - Address used 8800 blvd Lacroix
 * [x] Mobile display 3 fire hydrants
![borne batiment](https://user-images.githubusercontent.com/38532918/54127959-59837200-43e1-11e9-86a8-95482eb61837.png)
 * [ ] the approval section show only one and the number is not displayed
![Approbation inspection](https://user-images.githubusercontent.com/38532918/54127922-4a042900-43e1-11e9-8e55-f3b065901da9.png)

* [ ] We can't add firehydrant in the add firehydrant list(always empty mobile and web)

**Comment by iamkinetic** [comment]
@philipperobertgh 
* Le mobile affichait les bornes de TOUTES les inspections en cours. Il manquait un WHERE à la requête! 
* Le numéro des bornes s'affiche toujours dans tous les tests que j'ai fait dans la dernière heure.

**Comment by iamkinetic** [comment]
@philipperobertgh Et prend Ste-Hyacinthe pour faire tes tests, c'est à peu près la seule ville qui a ses bornes importées.
