### ISSUE TITLE
Survey texte format and table setting cannot be configured for reporting

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#495]
**Describe the bug**
Survey texte format and table setting cannot be configured for reporting

**Expected behavior**
Tag "@Inspection.SurveyAnswers@" should not generate "hardcoded" HTML text, table and/or any format setting.

**Screenshots**
Here, a test with texts (and the tag "@Inspection.SurveyAnswers@") in RED inside a table with defined width ...
![Capture d’écran 2019-03-12 à 11.07.24.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/f10dd6a1-924b-4959-bcc8-3b7686616046)

.... the result when générate the report ...
![Capture d’écran 2019-03-12 à 11.10.33.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ebd078c5-6ec8-4e00-88d8-fbec353feb4b)

**Comment by iamkinetic** [comment]
C'est la seule section de la version de Julien des rapports qui a survécu dans son état à peu près originale.

Tu voudrais pouvoir faire quelque chose du genre?

<inspection-survey>
 <group>
@group.name@
@group.description@
<answer>
@answer.question@  : @answer.answer@
</answer>
</group>
</inspection-survey>

C'est plus facile à dire qu'à faire parce que notre structure de questionnaire est très flexible et l'arbre des questions pourrait en théorie avoir autant de niveau qu'on voudrait (même si on limite présentement le niveau maximal à 2).

Je pense que je vais commencer à réfléchir à permettre l'utilisation d'un logiciel externe pour les rapports parce qu'on est déjà pas mal à la limite de ce qui me parait réaliste dans un outil custom fait dans CkEditor.

Je crois qu'on pourrait peut-être se permettre d'avoir quelque part dans le site où on pourrait configurer l'utilisation de ce logiciel externe.  CAUSE a les licences nécessaires pour faire un éditeur de rapport en utilisant la librairie XtraReport (de DevExpress) qui est celle que nous utilisons à l'interne.  Avec ce outil, nous aurions beaucoup plus de flexibilité dans l'édition des rapports.   C'est à réfléchir.

**Comment by jocelyncardinal** [comment]
Pour l'instant, le besoin est beaucoup plus modeste - Seulement que le PLACEHOLDER "@Inspection.SurveyAnswers@" utilise le format texte défini en mode design (comme les autre PLACEHOLDER font déjà). Il s'agit probablement de simplement enlever les tags HTML 'Harcodé" par Julien dans le HTML produit par le PLACEHOLDER (dans mon exemple, ce qui n'est pas en rouge). En meme temps, enlever la largeur du tableau qui doit etre aussi "hardcodé" (WITDH=) ...

**Comment by iamkinetic** [comment]
OK, pour récapituler:
* Ne pas avoir un style par défaut.
  * Probablement que tu n'aimeras pas que le texte des groupes et sous-groupes soit le même que les questions/réponses elles-même.
* Ne pas avoir de largeur par défaut.
  * Je pourrais mettre une largeur à 100% pour que ça prenne toute la largeur disponible du contenant dans lequel la variable est?

**Comment by jocelyncardinal** [comment]
**Oui**, pas avoir un style par défaut. Toutefois, je propose de conserver le **BOLD** pour le texte des groupes et sous-groupes (c'est deja comme ca) - ca devrait donner un résultats pas pire
Probablement que tu n'aimeras pas que le texte des groupes et sous-groupes soit le même que les questions/réponses elles-même.
**Oui**, ne pas avoir de largeur par défaut. Mettre une largeur à 100% ca me semble une bonne idée.

**Comment by iamkinetic** [comment]
Sera fait via #514.

**Comment by iamkinetic** [comment]
Ça donne ceci en pseudo html:

<h2>Catégorie</h2>
<h3>Sous-Catégorie</h3>
<table width=100%>
   <tr>
     <td width:35%>Question</td>
     <td width:65%>Réponse</td>
   </tr>
</table

À l'oeil c'est pas mal pareil comme avant, sauf que les largeurs sont en % au lieu d'être en dimensions fixes (c'était 8.5 pouces).

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/3968d325-6afb-49f7-83c6-d093d57e512d)
