### ISSUE TITLE
Reporting - Tags PipeLocation and CollectorLocation on BuildingAlarmPanel are useless

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#496]
**Describe the bug**
Reporting - Tags **BuildingAlarmPanel.PipeLocation** and **BuildingAlarmPanel.CollectorLocation** are useless

**Screenshots**
![Capture d’écran 2019-03-12 à 11.46.43.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/1e9905dc-242d-45c7-965c-c13de4fe1d05)

**Comment by iamkinetic** [comment]
* [ ] Stop using the same dto for the alarm panel and the sprinklers so we don't have extra fields.

**Comment by iamkinetic** [comment]
Sera fait via #501
