### ISSUE TITLE
Fire hydrant edition - make it look good

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#497]
We need to make this look better:

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/190f1b7e-128e-4148-9abc-80d879a36acf)

**Comment by philipperobertgh** [comment]
Doit-on pouvoir créer des bornes? 
Car les bornes font partie de la modification de readonly, donc l'ajout n'est pas accessible.

**Comment by iamkinetic** [comment]
Non.
