### ISSUE TITLE
Reporting configuration tool - The SAVE button doesn't work one time out of two

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#498]
**Describe the bug**
Reporting configuration tool - The SAVE button doesn't work one time out of two. For instance, when you press the SAVE button the first time then it works, the second time it doesn't work, the third time it works, the fourth time it doesn't work and so on ...

**Screenshots**
![Capture d’écran 2019-03-12 à 12.03.20.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/471d4f10-520a-48b9-a9ac-1c60e42509b6)

![Capture d’écran 2019-03-12 à 12.04.53.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/0dc93772-6b89-4352-af52-e04802b13b78)

![Capture d’écran 2019-03-12 à 12.05.02.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/f592e472-63a1-4ffc-b2bd-3be249754d80)

**Comment by iamkinetic** [comment]
* [ ] Make the save button work everytime it's being clicked.

**Comment by philipperobertgh** [comment]
* [ ] Ajouter la fonctionnalité de saut de page.

**Comment by jocelyncardinal** [comment]
Oui, ça serait vraiment super si tu pouvais en profiter pour faire l’ajout de la capacité de gérer les sauts de page.

Le 27 mars 2019 à 07:39, Phil <notifications@github.com<mailto:notifications@github.com>> a écrit :


  *    Ajouter la fonctionnalité de saut de pages

**Comment by iamkinetic** [comment]
https://stackoverflow.com/questions/38842628/ckeditor-prevent-page-refresh-on-clicking-save-button-on-toolbar-and-call-ow
