### ISSUE TITLE
Reporting - "Risques Particuliers" are generated even if there is nothing entered.

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#499]
**Describe the bug**
In report, "Risques Particuliers" are generated even if there is nothing entered.

**Expected behavior**
Should be printed if ...
**BuildingParticularRisk.IsWeakened** is TRUE or
**BuildingParticularRisk.HasOpening** is TRUE or
**BuildingParticularRisk.Comments** is not empty or
**BuildingParticularRiskPicture.DataUri** is not empty

**Screenshots**
![Capture d’écran 2019-03-12 à 15.14.32.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7ebb6422-a570-40ad-a096-131aa48e55b8)

![Capture d’écran 2019-03-12 à 15.10.54.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/610ba5c3-da5b-45ad-9e76-5bf55670b9e9)

**Comment by iamkinetic** [comment]
* [ ] Add a where condition to the particular risk's query: `IsWeakened || HasOpening || Comment Is not empty || DataUri is not empty` (pseudo code)

**Comment by iamkinetic** [comment]
Sera fait via #501
