### ISSUE TITLE
Make the report's editor a better

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#501]
* [ ] Add a where condition to the particular risk's query: `IsWeakened || HasOpening || Comment Is not empty || DataUri is not empty` (pseudo code) (see #499)
* [ ] Stop using the same dto for the alarm panel and the sprinklers so we don't have extra fields. (see #496)

**Comment by philipperobertgh** [comment]
Pas capable d'approuver une inspection avec de la protection incendie car celles-ci ne s'affichent pas dans l'écran des approbations.
