### ISSUE TITLE
Cannot generate report anymore after second inspection has been done on a same address

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#503]
**Describe the bug**
Cannot generate report anymore after second inspection has been done on a same address. Also, for the inspection date it take the last one for both (we lost the inspection date of the first one) 

**To Reproduce**
Simply re-assign another inspection on the same address which has been inspection completed yet

**Expected behavior**
Keep the Inspection date of the first inspection and allow generate the inspection reports for both inspection with the data capture at the time of the inspection. Report shall keep data unchanged from the inspection done at the inspection date (to keep the history)

**Screenshots**
![Capture d’écran 2019-03-14 à 12.00.21.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/23c58b36-9636-4e5e-bf88-d24505e6944f)

**Comment by iamkinetic** [comment]
##### Same date
Oui, la date de la **dernière** inspection est logiquement la même si on a deux fois le même bâtiment dans la grille.

##### Le rapport qui sort pas
La génération devrait fonctionner même si on voit deux fois le bâtiment pour deux inspections.  Par contre, le rapport a été initialement conçu pour que son point de départ soit un bâtiment et non une inspection.  Théoriquement, le rapport devrait afficher les données du bâtiment et de la dernière inspection complétée.

##### Par rapport au fait de vouloir avoir le rapport avec les données propres d'une inspection
Les informations de l'inspection sont en réalité les informations des bâtiments, donc si tu fais deux inspections sur un même bâtiment, ça se retrouve quand même dans la même table en finalité et le rapport va lire dans ces tables (Building, BuildingSprinkler, BuildingContact, etc).  Nous n'avons actuellement rien dans les tables qui nous dit de quelles inspections proviennent les informations.

La seule exception à cette règle est au niveau du questionnaire puisque c'est une sous-table de l'inspection.

**Comment by jocelyncardinal** [comment]
**Same date**
OK, donc il faudrait créer un nouveau champ "Date d'inspection"

**Le rapport qui sort pas**
OK je comprend, c'est toujours l'info la plus récente qui sera dans le rapport, les deux rapport seront identiques. Il faudrait quand meme réglé le fait que le générate ne fonctionne pas présentement

**Le rapport avec les données propres d'une inspection**

Donc impossible de revoir une inspection précédente via les rapports. Je présume que les inspections sont conservé dans la database (table inspection) et que ca pourrait éventuellement servir pour avoir acces aux données des inspections précédentes (l'historique). En ce qui concerne le besoin d'avoir fonctionnalité d'historique, il faudrait évaluer si c'est vraiment nécessaire, je ne suis pas certain du tout. C'est un questionnement a répondre via le projet-pilote ... 

Question: Est-ce qu'on conserve toutes les données des inspection dans la table Inspection? Je crois que oui et qu'on copie le contenu de la table inspection dans bâtiment une fois que ca été approuvé.

**Comment by iamkinetic** [comment]
On duplique temporairement le bâtiment et ses enfants pour ne pas faire l'inspection par dessus les données originales, puis on remet ça sur l'original une fois que l'inspection est complétée.

Théoriquement, on pourrait modifier un peu ça pour garder l'historique un jour.  

Pour l'instant on va s'arranger pour le rapport sorte.  Via le point #514.
