### ISSUE TITLE
Reporting - Missing fields in BuildingHazardousMaterial

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#504]
**Describe the bug**
There are 12 missing fields in BuildingHazardousMaterial prevent for reporting on it. See the screenshot below for details ...

**Screenshots**
![Capture d’écran 2019-03-14 à 11.57.25.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/280c969d-3e8b-4f39-a0ae-66cf94b40bcc)

**Comment by jocelyncardinal** [comment]
**Currently, we have only access to the 3 fields as display in the following screenshots...**

![Capture d’écran 2019-03-14 à 14.34.21.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a3ebea3c-9ee9-4f75-9cdb-bd44a45e4360)

**...and ...**

![Capture d’écran 2019-03-14 à 14.34.57.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/bfbf8f13-0652-4819-a415-071e8aaf68fe)

**Comment by iamkinetic** [comment]
Ouais, c'est possible que certaines tables soient incomplètes.  J'ai gardé les requêtes que Julien avait fait à quelques endroits et comme toutes les sections étaient hardcodées dans sa version, il avait fait les requêtes pour ne sortir que ce qu'il avait besoin. 

Est-ce que tu veux tous les champs manquants?

**Comment by jocelyncardinal** [comment]
oui, si possible.

**Comment by iamkinetic** [comment]
* [ ] Add missing fields to BuildingHazardousMaterial for report.

**Comment by iamkinetic** [comment]
Sera fait via #514.
