### ISSUE TITLE
Reporting -  @MainBuildingFireHydrant.Color@ display HEXADECIMAL code (FIXED)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#506]
**Describe the bug**
When reporting the place holder @MainBuildingFireHydrant.Color@ display HEXADECIMAL code !

**Screenshots**
![Capture d’écran 2019-03-14 à 15.35.23.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cba3475e-91c6-4fd3-8430-e1d5bd726355)

we get ...

![Capture d’écran 2019-03-14 à 15.35.11.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5d9c79ed-1ee9-4e64-b943-4db70af4093a)

**Comment by iamkinetic** [comment]
Well, that's what is stored in the database.  

Qu'est-ce que tu voudrais qu'on affiche?

**Comment by jocelyncardinal** [comment]
OK Cool, c'est bon je peux l'utilser comme style pour affiché la couleur directement ...

![Capture d’écran 2019-03-14 à 16 22 31](https://user-images.githubusercontent.com/32175949/54389120-c0b95480-4675-11e9-899a-61c0496ad790.png)

Ca donne ca ...

![Capture d’écran 2019-03-14 à 16 21 03](https://user-images.githubusercontent.com/32175949/54389157-d890d880-4675-11e9-94de-2f4c4dabfe23.png)

**Donc, problème réglé!**

Temporairement, j'ai affiché le code HEXA a titre indicatif.

**Comment by jocelyncardinal** [comment]
Pour discussion : Éventuellement, on pourrait ajouter un nouveau place holder **ColorName** @MainBuildingFireHydrant.ColorName@ qui afficherait la couleur en texte : "rouge", "vert", etc - il faudrait tenir compte de la langue et il faudrait gérer ca. Je ne suis pas certain que ca vaut la peine
