### ISSUE TITLE
Ability to give access to reports in HTML format

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#508]
**Is your feature request related to a problem? Please describe.**
Report in HTML format that would avoid seeing the problem of page breaks. That brings a questioning ... the HTML format could be more appropriate than PDF since typically the report would be viewed from a web browser. The reports will probably not be used much in paper format (to validate) except in case we want to generate letters to the citizen (the HTML format would still be OK).  Given the inability to handle page breaks with HTML, it would not be easier to eliminate the PDF generation and only keep the HTML? 

**Describe the solution you'd like**
Provide the ability to generate the HTML report a from the same "Generate" button. Simply duplicate all reports item in the dropdown list. Here, an exemple ... 

![Capture d’écran 2019-03-15 à 22.36.27.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fe2c5ca0-d5fb-468d-b0a9-92f1364f76fa)

**Describe alternatives you've considered**
A web link accessible directly from the list of completed inspections (take the default report for instance) which would require to generate reports in HTML in advance on the server.

**Comment by iamkinetic** [comment]
Est-ce que le but du html est simplement d'avoir le page break?  Je ne suis toujours pas sûr de comprendre l'utilité de tout ça.

**Comment by iamkinetic** [comment]
Si le but est simplement d'avoir un page break, il existe un plugin pour CkEditor pour ça:

https://stackoverflow.com/a/38014496

@philipperobertgh

**Comment by iamkinetic** [comment]
Peut-on fermer ce point?

**Comment by jocelyncardinal** [comment]
oui
