### ISSUE TITLE
Export of completed inspections to CAUCA software intervention card (Fiche d'intervention)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#511]
**Is your feature request related to a problem? Please describe.**
The information collected during the inspection visits by the prevention agents must be available during the intervention.  In addition to the "Calling card", the "Cauca software intervention card" must be updated accordingly.

**Describe the solution you'd like**
Export of completed inspections to CAUCA software intervention card (Fiche d'intervention). Ideally, all the fields already present in the CAUCA software "fiche d'intervention" should be updated. This is what is printed at the fire station accompanying the calling card during an intervention. Here are some screenshots that shoes the data to be synchronized ...

![Capture d’écran 2019-03-18 à 14.21.26.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/3fb942d6-7ece-4c95-8b88-70dc52c3b65c)

![Capture d’écran 2019-03-18 à 14.21.47.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/d0f7332b-2abc-4eb4-bcbd-be866f615a84)

![Capture d’écran 2019-03-18 à 14.26.02.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/327e9df1-d2c5-4add-9fae-d6b79e30730c)

**Describe alternatives you've considered**
Note that in the possibility or software Cauca would eventually be replaced by SURVI-Prevention (or equivalent), **this request could become obsolete.**

**Comment by iamkinetic** [comment]
On ne va pas exporter de SURVI-Prévention vers les fiches d'intervention CAUCA.  La structure est complètement différente et les fiches CAUCA est un produit agonisant.

Par contre, les PDFs de SURVI-Prévention seront ceux qui seront rendus disponibles en cas d'intervention (SURVI Véhiculaire, SURVI Mobile, etc).

Les PNAPS, matières dangereuses, contacts et quelques trucs des bâtiments sont aussi exportés vers CAUCA et disponible dans le logiciel de répartition et autres outils.

**Comment by iamkinetic** [comment]
Le rapport sort même quand il y a deux inspections dans mes tests.

**Comment by iamkinetic** [comment]
J'ai quand même ajoutée la date de fin de l'inspection dans l'onglet des inspections complétées et on pouvait déjà voir qui a fait l'inspection:

C'est pas l'exemple du siècle parce que j'ai fait deux inspections sur le même bâtiment dans la même journée, mais ça te donne une idée.

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/50906e19-6621-42f6-9b31-3d290db64129)
