### ISSUE TITLE
User Management validation on fire safety department

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#513]
When creating a user the fire safety department assignment should be required to avoid city filtering errors.
Add required validation on department control in webuser.component.ts

**Comment by iamkinetic** [comment]
On va attendre la réponse officiel du maître des dockers et s'il confirme qu'on ne met pas la version nul part tu pourras lui expliquer ce qu'on veut (mettre la version dans package.json).
