### ISSUE TITLE
The version displayed in the menu is not the good one

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#519]

**Comment by philipperobertgh** [comment]
Pour la récupération de la version de l'application, dans le projet web nous n'avons pas de fichier config.xml. La seule version que nous avons est dans le package.json, cependant cette version devrait-être  gérée par le docker à partir du tag dans Git.
Est-ce que cette gestion a été mise en place dans le docker ?

**Comment by iamkinetic** [comment]
ST-2060

**Comment by iamkinetic** [comment]
@philipperobertgh Considère que la correction et fait comme si ça marchait.  On affichera "__version__" en attendant que ce soit vraiment fait.  Donc mettons ce point à "tester".
