### ISSUE TITLE
Image does not print in report (No2)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#520]
**Describe the bug**
Image does not print in report 

**Screenshots**
![Capture d’écran 2019-03-25 à 11.20.23.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/9123e65e-17b5-479a-be98-5cbb78b79de4)

**Comment by jocelyncardinal** [comment]
Reporting - Image does not print in report#463

**Comment by iamkinetic** [comment]
Quel rapport?

**Comment by jocelyncardinal** [comment]
N’importe lequel - prend RapportCauca

Le 26 mars 2019 à 13:20, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


Quel rapport?

**Comment by jocelyncardinal** [comment]
Still doesn't works
