### ISSUE TITLE
Cannot generate report anymore after second inspection has been done on a same address (no2)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#523]
**Describe the bug**
Cannot generate report anymore after second inspection has been done on a same address (no2)

**Screenshots**
![Unknown.jpeg](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fe3e0812-781e-49e0-8480-da307dacd513)

**Comment by jocelyncardinal** [comment]
Cannot generate report anymore after second inspection has been done on a same address #503

**Comment by iamkinetic** [comment]
Dans quelle ville est l'inspection problématique?  Le screenshot est tellement petit que c'est pas mal illisible.

**Comment by jocelyncardinal** [comment]
La ville est Waterville 

Tu peux accéder à l’inspection avec user patrick.giguere / ereugig1234

**Comment by iamkinetic** [comment]
Ouin, l'API retourne une erreur 500 pour cette inspection.

**Comment by iamkinetic** [comment]
C'est un bug causé par les données.  La structure est celle-ci :

* Anomaly -> AnomalyPicture -> Picture.
  * L'anomalie a une ou plusieurs anomaliePicture qui pointe vers l'image.

Dans le cas présent, l'AnomalyPicture ne pointe vers rien et le code du rapport n'était pas fait pour supporter cette éventualité.

Je vais corriger ça.

**Comment by iamkinetic** [comment]
D'ailleurs, je vois les images dans le rapport de cette inspection! ;-)

**Comment by jocelyncardinal** [comment]
Oui je me souvient avoir créé une anomalie avec images et ensuite fait quelques manipuler les images (possiblement fait un delete???)

**Comment by jocelyncardinal** [comment]
OK, donc ça va réglé le problème des images qui s’imprime pas en même temps 😊

**Comment by iamkinetic** [comment]
Non, c'est juste que je vois des images pour ces rapports, mais ma correction ne fera pas qu'une image qui ne s'affiche pas s'afficherait.

**Comment by jocelyncardinal** [comment]
D’accord mais ça nous fait au moins un cas ou une  image s’imprime. On avance 😊
