### ISSUE TITLE
 Sometimes it shows the name of the lots in the completed inspections

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#524]
**Describe the bug**
 Sometimes it shows the name of the lots in the completed inspections

**Screenshots**
![Capture d’écran 2019-03-25 à 11.17.39.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7a831385-638c-4c03-8d96-4f773f600b58)

**Comment by iamkinetic** [comment]
Quand tu fais quelque chose de particulier?

**Comment by jocelyncardinal** [comment]
Non, j’ai pas remarquer quelques chose de particulier. J’ai juste remarqué ...

Le 26 mars 2019 à 13:21, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


Quand tu fais quelque chose de particulier?

**Comment by iamkinetic** [comment]
Répété!  Le problème semble survenir quand on change d'onglet vraiment vite.

Peut-être faudrait-il regarder pour empêcher le changement d'onglet pendant qu'on load déjà l'onglet courant.
