### ISSUE TITLE
Cannot delete report

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#528]
**Describe the bug**
if we delete a report, the report disappear but it is not really deleted since it will come back as soon as you refresh the window.

**Screenshots**
Press the garbage button ...

![Capture d’écran 2019-04-01 à 15.45.11.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/6c997214-6a97-42e4-a208-cdfcb38468b7)

Click 'yes'

![Capture d’écran 2019-04-01 à 15.45.22.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/79ee4cf4-cb7f-4512-840f-42bd52ea6796)

The report disappear but it is not really deleted since it will come back as soon as you refresh the window.

**Comment by iamkinetic** [comment]
On peut dire que le bouton poubelle est un vrai déchet!

Le problème est que la page affiche les rapports inactifs.  La suppression elle-même fonctionne parfaitement.
