### ISSUE TITLE
Cannot start the questionnaire ("cantStartBecauseNotDownloadedAndApiUnvailable")

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#531]
**Describe the bug**
Cannot start the questinnaire ("canStartBecauseNotDownloadedAndApiUnvailable")

**Screenshots**
That inspection assigned to Jocelyn Cardinal ... 
![Capture d’écran 2019-04-04 à 11.02.18.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/8754d481-102f-43e0-8eab-24d5c10f479a)

Log In App Mobile version 1.6.0 as Jocelyn Cardinal go to the inspection and click DÉMARRER button ...

![Capture d’écran 2019-04-04 à 11.06.50.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/acbb79e5-2a59-4a09-88f5-d9616b493320)

**Comment by jocelyncardinal** [comment]
- The problem seems to happen **only for that specific address : "0 chemin du martinet" ** 
- Does not seem to be related to the fact that this is undefined risk since (non defini) because i tested with others 'non defini' and it works

**Comment by iamkinetic** [comment]
cantStartBecauseNotDownloadedAndApiUnavailable is the unlocalized label, which means we're probably missing the french localization for this label.

This message is displayed when the inspection couldn't be downloaded.

**Comment by iamkinetic** [comment]
The problem is that some of the field in InspectionBuildingContact have a shorter maximum length than than BuildingContact.  This is a database issue.

**Comment by iamkinetic** [comment]
I'll fix the database issue, but not missing localization label.  It would take too long for such a trivial bug.  I'll create another issue so we can fix it in the future.

**Comment by iamkinetic** [comment]
Missing localization's issue : #330

**Comment by iamkinetic** [comment]
@jocelyncardinal please try again.

**Comment by jocelyncardinal** [comment]
It works now! Gréât job!

Le 4 avr. 2019 à 12:52, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jocelyncardinal<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7C9569675d88d64220dcb608d6b91dfccd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636899935770494526&sdata=5lIOBKaAQllYyI0XWTPpSw6cQqsiyouhzTIa5xp%2BUiA%3D&reserved=0> please try again.
