### ISSUE TITLE
Image does not print in report (No3)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#532]
**Describe the bug**
Same issue #463 and #520 

**Screenshots**
This inspection with images in Plan d'intervention and 2 images in the Anomalie
![Capture d’écran 2019-04-04 à 11.42.48.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cc8bd01a-3eb6-419b-8cc2-6b6799d00efd)

Generated this report ...
![Capture d’écran 2019-04-04 à 11.43.00.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/950167b4-3a4f-46da-95c2-056f5d57f745)

Images are not printed ...
![Capture d’écran 2019-04-04 à 11.41.08.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/80c8c8b4-b1cb-4088-8562-c43b4c49748f)
![Capture d’écran 2019-04-04 à 11.41.16.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/37b38cc1-1f84-446c-b98c-d42c24ece2c7)

From the app mobile ...
![IMG_0975.jpg](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/dd987c72-e54e-4e87-9c01-b2d9fe4d6953)

**Comment by iamkinetic** [comment]
Which city?

**Comment by jocelyncardinal** [comment]
Sainte-Anne-des-Lacs

**Comment by jocelyncardinal** [comment]
Désolé, j'ai ajouté la colonne pour les prochaine fois :) 

![Capture d’écran 2019-04-04 à 11.54.06.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/1b57987c-1bc8-4816-8733-1eb82767ed12)

**Comment by iamkinetic** [comment]
Pictures are correctly generated in the pdf when running SURVIP and SURVIP-WebApi on Windows.  

Is it a linux related problem?

**Comment by iamkinetic** [comment]
I guess that explain why we were under the impression that there was no bugs in previous version.

**Comment by iamkinetic** [comment]
I've look at the wkhtmltopdf github issue's page and didn't found much.

**Comment by iamkinetic** [comment]
Ok, Daniel (le responsable des installations de SURVI-Prévention sur le serveur linux) et moi on s'est assis et on a regardé ça un peu plus en détail pendant la dernière heure.

D'après nos tests, il semble que la version de wkhtmltopdf (0.12.3.2) utilisée dans le docker ubuntu de l'API ait ce problème, mais que la version 0.12.4 n'ait pas ce problème.  

Le problème est que wkhtmltopdf 0.12.4 n'existe pas en package Ubuntu.  Comme ça va prendre un certain temps pour trouver une solution propre, il va devoir prévoir ça son horaire.  Ça va donc prendre quelques jours avant que ce soit réglé.

**Comment by jocelyncardinal** [comment]
Bien reçu! Merci pour l'investigation rapide.

**Comment by iamkinetic** [comment]
Pour ref: JIRA ST-2106

**Comment by iamkinetic** [comment]
La balle est maintenant dans mon camp, dès que j'aurai testé la solution des techs, on pourra déployer ça.  Je suis un brin occupé aujourd'hui, ça ira probablement donc à la semaine prochaine.

**Comment by jocelyncardinal** [comment]
Parfait! Merci de me tenir au courant et aucun problème pour remettre ça la semaine prochaine en ce qui me concerne.

**Comment by iamkinetic** [comment]
J'ai "rendez-vous" avec les techs pour régler tous les problèmes qui restent ce matin.  La correction devrait finalement arriver bientôt!

**Comment by iamkinetic** [comment]
Bon, j'ai finalement testé les changements qu'ils ont fait et ça semble fonctionner à merveille.  Les gars vont s'occuper de mettre à jour l'installation de test dans les prochaines minutes.

**Comment by jocelyncardinal** [comment]
Super! Juste me faire savoir quand le site de test va être a jour, je vais tester ca

**Comment by iamkinetic** [comment]
C'est fait.  Testé avec 785, Rue Couvent de mon côté.

**Comment by jocelyncardinal** [comment]
J’ai fait quelques tests rapides et je confirme que ça fonctionne très bien de mon côté aussi. Toutes les images (incluant les logos) s’impriment correctement (résolution et ratio). Great job!!!

**Comment by iamkinetic** [comment]
Pour fin d'historique : nous avons changés la version de wkhtmltopdf, mais nous avons également augmenté la quantité de RAM attribuée à l'API parce que certains rapports faisaient que le kube dépassait sa limite, était redémarré automatiquement et faisait que le rapport sortait pas (error 500).
