### ISSUE TITLE
Civic number in dialogue of the "Lot" is not wide enough

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#534]
**Describe the bug**
Civic number in dialogue of the "Lot" is not wide enough

**Screenshots**
![Capture d’écran 2019-04-05 à 10.29.47.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/491e95fe-83d3-4878-b866-419654cdab93)

**Comment by iamkinetic** [comment]
That's the side effect of having a grid.  if the form is narrower, the grid's columns will be too.  I'm not sure what we can do about this problem.

**Comment by iamkinetic** [comment]
We could make the column's width resizable though.

**Comment by iamkinetic** [comment]
@jocelyncardinal

Voici ce que j'ai changé :
* La largeur des colonnes est maintenant "resizable".
* Le popup d'édition du lot est maintenant full screen plutôt que de prendre genre 70% de la taille du browser.
* J'ai ajouté un peu de couleur parce qu'en plein écran ça faisait blanc longtemps.

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/a6242bec-1576-4cee-828c-a5a0a63e431a)

**Comment by jocelyncardinal** [comment]
parfait!
