### ISSUE TITLE
Ensure that the information is always synchronized between the mobile app and the website (validation only)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#535]
Ensure that the information is always synchronized between the mobile app and the website after a REFRESH of the web page. Note that this is a very minor issue that has been difficult to reproduce. So, not yet a bug report to me because it does not prevent user to do their job at all. But this is something that we could get advantage to check for validation only.

Here is what seems to have happened: The inspection was started (START button pressed) but no data was entered yet in the questionnaire. The mobile app then said "inspection in progress" and at the same time the website "to do" even I had pressed the REFRESH button repeatedly. However, the website became OK (In progress) as soon as the questionnaire started

![Capture d’écran 2019-04-05 à 10.32.41.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/71f33cbb-9070-4112-95ba-b4257d795a51)

**Comment by iamkinetic** [comment]
That looks like a side effect of having an offline mode.  If the inspection is started while being offline, the server won't know about it.

There's absolutely no synchronization being done with the server when doing the inspection except:
* When starting the visit if the API is available.
* When ending the visit if the API is available (or once the inspection is uploaded).

The mobile application should not call the API when starting the survey.  I don't think it does, but it's not impossible we have forgot to remove a call or something.
