### ISSUE TITLE
Sort and filter grid problems

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#536]
* [ ] We have to allow the sort on multiple columns (check option for devextreme grids)
* [ ] We must allow the insensitive filter in grids (may need web-api changes)
Ex.:
 Batch editing grid
 Batch Building search

**Comment by iamkinetic** [comment]
Une requête odata ne peut pas être case insensitive.  Il faudrait que la BD ait une collation "case insensitive accent sensitive" pour qu'en s'en sorte.  Toute autre solution sera un patch horrible & lent.

@jocelyncardinal j'ai ajouté la possibilité de mettre un tri sur plusieurs colonnes.  Il faut tenir "shift" en cliquant sur le titre de la colonne OU ajouter le tri par le menu contextuel de la colonne pour se servir de cette fonctionnalité.  Je l'ai mis à deux endroits : tableau de bord + grille d'ajout de bâtiment dans la fenêtre d'édition d'un lot.
