### ISSUE TITLE
The ordering of the questionnaire does not work properly (using the up and down arrows)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#537]
**Describe the bug**
The ordering of the questionnaire does not work properly. It is very easy to see the problems simply by using the up and down arrows. I got problems multiples times. Use this questionnaire for instance ...

![Capture d’écran, le 2019-04-23 à 17.33.34.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/c3be372e-3aa8-44de-87b4-c86b814c444f)

For exemple, select item 6 and click the UP arrow to make it above the item 6.1 - it does not work!
![Capture d’écran, le 2019-04-23 à 17.36.01.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/40f18b28-b19f-4b4b-9891-15b3e9a3ea67)

Note a good hint about this the problem - when you select the item 6 it show the wrong item description on the right side ???
![Capture d’écran, le 2019-04-23 à 17.43.03.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/564cd537-9283-4d76-a5eb-7bac3c3b6951)

**Comment by jocelyncardinal** [comment]
** Others info **
I got many problems when I try to orders these items ...
![Capture d’écran, le 2019-04-23 à 17.31.40.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5981c0ff-83bd-4c8e-90f0-60ea4553727b)

**Comment by iamkinetic** [comment]
Tell me how much of a deal breaker this is so I can decide if we need to have it prioritized for a quick fix.

**Comment by jocelyncardinal** [comment]
This problem really prevents the use of the questionnaire configuration page. Moreover, it results from a corruption of the data which seems to be a major problem (example item 6).  In my opinion, it is a priority to examine this problem quickly.

**Comment by iamkinetic** [comment]
@jocelyncardinal Est-ce qu'on attend les statistiques avant de faire la mise à jour qui règle ce problème?

**Comment by jocelyncardinal** [comment]
Oui, faire la mise à jour en même temps que statistiques.

De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip <reply@reply.github.com>
Date : jeudi 25 avril 2019 à 12:18
À : CAUCA-9-1-1/survip <survip@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Mention <mention@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip] The ordering of the questionnaire does not work properly (using the up and down arrows) (#537)


@jocelyncardinal<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7C4ca54d79ae8d46caaed908d6c9999d7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636918058935896223&sdata=mMbU588nKwZzhjYKs9jvbNZ94WW7yazEzLLThq%2BaUL0%3D&reserved=0> Est-ce qu'on attend les statistiques avant de faire la mise à jour qui règle ce problème?
