### ISSUE TITLE
 Validate the operation for refusals and absences during inspections

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#542]
For "refusals" and "absences" the inspection is not sent automatically to the server. We must do it by clicking the "send to server" button

![Capture d’écran, le 2019-05-15 à 15.37.24.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/9bc15de6-7c01-474f-b8bf-74c570850830)

After it has been sent, it is possible to approved the inspection without restriction ?

![Capture d’écran, le 2019-05-15 à 15.27.04.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/91527e2a-4bc6-47ca-af8e-9102cf7d5d60)

![Capture d’écran, le 2019-05-15 à 15.29.40.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/01e0ae78-3b97-4b1e-94bc-0e4197646752)

**Comment by jocelyncardinal** [comment]
Also, add a new inspection date doesn't seem to work.   

![Capture d’écran, le 2019-05-15 à 15.47.59.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/e5c66d75-1384-46cd-b52c-4ed1df444d97)

**Comment by iamkinetic** [comment]
Reproduced:
* Inspection is not correctly sent back to the server (or not set as sent on the mobile?) once a visit is refused or owner is absent.

**Comment by iamkinetic** [comment]
Pour clarifier le fonctionnement de "Refuser" ou "Absence":
* L'inspection retourne au statut "En attente d'inspection.
* La visite devient avec le statut complété.
* Lorsqu'on choisit une date de prochaine visite, la prochaine visite est aussitôt créé avec le statut "À faire" avec la date choisie.

Ce qu'il faut savoir :
* La notion de date des visites est complètement inutilisé à part à cet endroit.  La date de visite ne fera pas que l'inspection est visible ou non sur le mobile.

Donc si on refuse une inspection, elle sera immédiatement visible sur l'appareil mobile, ce qui peut donner l'impression que le refus n'a pas fonctionné.

À faire un jour :
* Ne pas afficher les inspections tant que la date de visite n'est pas plus petite ou égale à "maintenant".

**Comment by iamkinetic** [comment]
Il y avait aussi quelques problèmes avec le démarrage d'inspection quand une visite avait déjà été créé lors d'un refus précédent.
