### ISSUE TITLE
The questionnaire can not be completed because the "NEXT" button is always disabled (GRAY)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#543]
**Describe the bug**
The questionnaire can not be completed because the "NEXT" button is always disabled (GRAY)

**To Reproduce**
The problem happen with this questionnaire:
![Capture d’écran, le 2019-05-22 à 10.22.02.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/2d9a3019-7898-48fb-9560-3f88991c4113)

Select this Questionnnaire for SSI
![Capture d’écran, le 2019-05-22 à 10.25.13.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a2c3ce3a-4ecb-4b8d-9305-ba44d3e6983b)

Create a lot
![Capture d’écran, le 2019-05-22 à 10.28.46.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/9f84d6cd-0296-4265-8f48-b31eba2dcc95)

Start the inspection from App Mobile
![Capture d’écran, le 2019-05-22 à 10.37.59.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/6a9bbf4e-cbc6-4706-abee-dea19fd70e8d)

and then on question #4, it is not possible toe click the "NEXT" button because it stay disabled 
![Capture d’écran, le 2019-05-22 à 10.32.49.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/dd3ececa-ccc9-4425-bc2e-cb1586b29fd4)

**Comment by iamkinetic** [comment]
@philipperobertgh Peux-tu jeter un coup d'oeil là dessus svp?  À mon avis le bug en est un de séquence.

Voici la requête qui sort les questions si tu veux jeter un coup d'oeil :
```
select s.name, sq.id, sq.sequence, sq.id_survey_question_next, sq.id_survey_question_parent
From survey_question as sq
inner join survey_question_localization s on sq.id = s.id_survey_question and s.language_code = 'fr'
where sq.id_survey = 'e03e1dc4-094f-4bd1-8672-0d187d067ec4' and sq.is_active = true
order by sq.sequence
```

**Comment by iamkinetic** [comment]
@jocelyncardinal Le problème vient du faire que la question suivante des choix qui ne fonctionne pas a été effacé, mais que les choix pointent encore sur cette question inactive.  Tu peux voir ça quand tu cliques sur le crayon du choix, tu vas voir l'id de l'ancienne question au lieu du texte de la question.

**Workaround temporaire** : mettre une nouvelle question suivante.

**Solutions réelles possibles** (*en choisir une svp*) :
* Empêcher de supprimer une question qui est utilisée comme question suivante ailleurs dans l'arbre.
* Demander à l'usager de confirmer ("Supprimer cette question fera que certaines questions ou choix perdront leur question suivante, voulez-vous continuer?").

**Comment by iamkinetic** [comment]
Sera corrigé via #548 quand on saura quelle solution tu préfères.

**Comment by jocelyncardinal** [comment]
**Solutions No 2**:  "Demander à l'usager de confirmer ("Supprimer cette question fera que certaines questions ou choix perdront leur question suivante, voulez-vous continuer?").
