### ISSUE TITLE
Incorrect and missing fields for hazardous materials when generating reports

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#544]
**Describe the bug**
Incorrect and missing fields for hazardous materials when generating reports

Incorrect fields:
@BuildingHazardousMaterial.TankType@ 
@BuildingHazardousMaterial.Container@
@BuildingHazardousMaterial.Floor@

Missing fields:
@BuildingHazardousMaterial.Sector@

**Screenshots**
Here, the usage of field in report design (note that there is no available field for sector)
![Capture d’écran, le 2019-05-14 à 11.03.20.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/c9fb51b9-0a6a-4f8c-8cd6-610f445289bb)

Here, I tested with values entered in app mobile (captured during approbation)
![Capture d’écran, le 2019-05-14 à 10.59.42.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/49c950e3-0d61-47dd-8574-08d3be557cfd)

and then the result
![Capture d’écran, le 2019-05-14 à 11.06.06.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a08bc698-1043-40ab-a2db-1f42d3817baf)

You can see that TankType and Container are mixed and the Floor use printed the TankType

**Comment by jocelyncardinal** [comment]
**More testing ** 
![Capture d’écran, le 2019-05-14 à 10.39.21.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4f86af27-7e95-47e8-ba49-6abe20fbb445)

**Comment by jocelyncardinal** [comment]
You can use "Rapport Waterville (14 mai)" for testing ...

![Capture d’écran, le 2019-05-22 à 15.17.57.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a3d338a0-d54b-4453-a912-446f04310793)

**Comment by iamkinetic** [comment]
* Sector is indeed missing and will be added.
* TankType : Should be alright, won't be changed.
* Container : Seems alright as well, won't be changed.
* Floor : is incorrectly set with the same value as the Container attribute and will be fixed.
