### ISSUE TITLE
Reporting - Cannot fix a size to logo or images (height is hardcoded)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#547]
The height of the Logo is always 100 pixel and for an image 400 pixel.

![Capture d’écran, le 2019-05-22 à 16.07.56.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/140fc9fb-c7f4-4286-902c-fe73ec500652)

I tried to override it in the report using table without success.

Logo  ...
![Capture d’écran, le 2019-05-22 à 16.03.43.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cbb33f52-11a1-40e7-94b1-183f0e0da5d0)

Image ...
![Capture d’écran, le 2019-05-22 à 16.05.47.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/e4391001-945f-48f4-a006-c401f6088d99)

Image ...
![Capture d’écran, le 2019-05-22 à 16.06.18.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/d543da77-7994-4d2a-917d-fc7d514dd49c)

**Comment by jocelyncardinal** [comment]
I don't know yet what would be the best solution. Here, some proposal to discuss ...

1. May be remove the the hardcoded height from fonction GetTag() or GetTagForLogo() used to generated to HTML. I am not sure if then it would be possible to set the size of the image by using the table/cell witdh and height ???

2. Use the the Image Icon from the report editor from
![Capture d’écran, le 2019-05-22 à 16.19.44.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/c4ba665d-f211-43bf-a247-482fda68c922)

**Comment by iamkinetic** [comment]
Your number 2 would be what I would try first.

**Comment by jocelyncardinal** [comment]
Would be the best to me too ... Not the the dialog prevent us to not enter a URL. Can we use that field to identify the image?

**Comment by iamkinetic** [comment]
Url would be @mainbuilding.siteplan@

**Comment by jocelyncardinal** [comment]
Good! And for other images, the URL would be ...

@MainBuilding.FireSafetyLogo@
@BuildingAnomalyPicture.DataUri@
@BuildingParticularRiskPicture.DataUri@

**Comment by Jeepsboucher** [comment]
@jocelyncardinal Finalement, on doit changer la grandeur avec le tag. Il suffit de rajouter un point avant de refermer le tag et d'inscrire la hauteur que l'on veut avoir
Ex: @BuildingParticularRiskPicture.DataUri.400@
Il y a toujours les hauteurs par défaut , 100 pour le logo et 400 pour un tag, donc même si l'on ne change pas un rapport on peut toujours l'utiliser.

**Comment by jocelyncardinal** [comment]
D’accord, ça me semble une très bonne idée! On inscrit seulement la hauteur (Height en HTML) et on n’inscrit rien pour largeur (Width) qui ainsi « s’ajuste » automatiquement pour conserver l’aspect ratio - comportement par défaut lorsqu’on inscrit pas Witdh en HTML il me semble

**Comment by jocelyncardinal** [comment]
D’accord, ça me semble une très bonne idée! On inscrit seulement la hauteur (Height en HTML) et on n’inscrit rien pour largeur (Width) qui ainsi « s’ajuste » automatiquement pour conserver l’aspect ratio - comportement par défaut lorsqu’on inscrit pas Witdh en HTML il me semble
