### ISSUE TITLE
Questionnaire - For groups of questions the minimum and maximum occurrence does not work

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#549]
**Describe the bug**
For groups of questions the minimum and maximum occurrence does not work

**To Reproduce**
Set  minimum and maximum occurrence mix max to zero ...
![Capture d’écran, le 2019-05-23 à 11.59.08.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/e9f8c003-54fc-440e-81f1-b82b7c48abde)

... in app mobile it is impossible to make zero occurence ...

![Capture d’écran, le 2019-05-23 à 12.19.32.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7151bf09-ca7f-4cc5-b070-2f34ca7cc79f)

**Expected behavior**
Should use properly the minimum and maximum occurrence that has been set. Note that If maximum is set to zero, it would mean "no maximum limit". 

**Work around **
For the time being as work around we added an option "No item" that the user can to select ...
![Capture d’écran, le 2019-05-23 à 12.18.42.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/3305b31c-7669-4510-a044-108110df41e3)

**Comment by jocelyncardinal** [comment]
Idea: When the minimum occurrence is zero, we could initialy have no item. Then the user must click the "+" button to add one or click "next" to go to the next question if there is no item to be added.

**Comment by iamkinetic** [comment]
@philipperobertgh Dis-moi donc ce que tu penses de ça svp

**Comment by philipperobertgh** [comment]
SI les limites d'occurrences ne fonctionnent pas dans le mobile, il faut les corriger. Donc je suis d'accord que si l'occurrence minimale est de 0 on devrait pouvoir passer à la question suivante sans ajouter d'item.

**Comment by jocelyncardinal** [comment]
Si l'occurrence minimale est de 0 on devrait pouvoir passer à la question suivante sans ajouter d'item mais il faudrait aussi conserver la possibilité d’ajouter un item (avec le petit bouton «+ » en haut à droite)

**Comment by iamkinetic** [comment]
Ok, on va améliorer ça aussi.  Les changements se feront uniquement dans l'application mobile, donc ce sera plus long avant que tu aies cette correction parce que je suis en train de faire la migration vers Ionic 4 et que ça me prendra encore au moins une semaine.  Lorsque ce sera terminé, on pourra faire la correction.

**Comment by iamkinetic** [comment]
Blocked by #295.

**Comment by iamkinetic** [comment]
Je ne crois pas que ce changement sera fait avant le mois de juillet.  Je dois d'abord terminer l'upgrade vers Ionic 4.

**Comment by jocelyncardinal** [comment]
Ce n’est pas une issue bloquante - Le work-around est OK et on peut attendre sans problème pour juillet

**Comment by iamkinetic** [comment]
FYI je me suis remis à l'upgrade vers ionic 4 vendredi et je travaillerai là dessus cette semaine.

**Comment by iamkinetic** [comment]
PRE-413

**Comment by philipperobertgh** [comment]
Issue moved to [CAUCA-9-1-1/survip-mobile #338](https://github.com/CAUCA-9-1-1/survip-mobile/issues/338) via [**ZenHub**](https://www.zenhub.com/)
