### ISSUE TITLE
Report print a blank page on production site surviprevention.cauca.ca

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#552]
**Describe the bug**
Report print a blank page on production site surviprevention.cauca.ca

**To Reproduce**
![Capture d’écran, le 2019-06-03 à 15.10.18.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/b7659773-44c3-4f87-bd79-5f591514a2f8)

![Capture d’écran, le 2019-06-03 à 15.12.48.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/8a3559d1-93eb-480e-b32a-98a9f2530694)

**Comment by iamkinetic** [comment]
Si c'est un bloqueur pour toi, fais-le savoir parce qu'il ne me reste que 2 jours avant mes vacances et je suis pas mal dans le jus! ;)

Puisque les installations utilisent le principe de container (Docker) et Kubernetes, tous les environnements devraient avoir exactement la même configuration à l'exception de la base de données.

**Comment by jocelyncardinal** [comment]
Oui, c’est assez bloquant. Est-ce que tu pourrais transférer l’issue à quelqu’un qui pourrait faire le suivi pendant tes vacances?

Le 4 juin 2019 à 08:18, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


Si c'est un bloqueur pour toi, fais-le savoir parce qu'il ne me reste que 2 jours avant mes vacances et je suis pas mal dans le jus! ;)

Puisque les installations utilisent le principe de container (Docker) et Kubernetes, tous les environnements devraient avoir exactement la même configuration à l'exception de la base de données.

**Comment by iamkinetic** [comment]
Je vais voir à ça.

**Comment by iamkinetic** [comment]
Je ne suis pas trop sûr qu'on comprend pourquoi ça n'affecte que l'environnement de prod, mais @Jeepsboucher pense avoir trouver la solution (ça marche sous Windows du moins).

**Comment by jocelyncardinal** [comment]
Je confirme que la solution  @Jeepsboucher<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeepsboucher&data=02%7C01%7C%7C8f095b09ff3c4d1452a508d6e9246196%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636952739793209728&sdata=RnJs8a7gJV6jOT07fjZkzlzcY5ODOXAoOWt%2BHVuGq84%3D&reserved=0> fonctionne. BRAVO!

**Comment by jocelyncardinal** [comment]
Je confirme que la solution  @Jeepsboucher fonctionne. BRAVO!
