### ISSUE TITLE
No toolbar on newly created report 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#553]
**Describe the bug**
No toolbar on newly created report 

**To Reproduce**
Create a new report 

**Screenshots**
HEre, a exemple ...
![Capture d’écran, le 2019-07-17 à 13.18.14 copie.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4e1fd24c-b119-47ba-92b8-68c52f1844df)

![Capture d’écran, le 2019-07-17 à 13.18.50 copie.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/d1ce81c7-26fd-4f1b-9bab-9d7ffcc9286a)

**WORK AROUND**
Simply duplicate any report and empty it (very easy)

**Comment by iamkinetic** [comment]
Reproduit en Test et en Prod.

**Comment by iamkinetic** [comment]
PRE-424
