### ISSUE TITLE
Inspection on CAUCATown that cannot be completed

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#555]
**Describe the bug**
Inspection on CAUCATown that cannot be completed.

**To Reproduce**
![Capture d’écran, le 2019-07-15 à 17.06.49.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/d1bf814d-a535-48b2-8895-071ba45abbbd)

**WORKAROUND**
"Ready for inspection" option has been unchecked to prevent mobile app to display

**Comment by jocelyncardinal** [comment]
![Capture d’écran, le 2019-07-23 à 18.19.39.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/9f096bae-f239-48e8-aed7-56772119a8eb)

**Comment by iamkinetic** [comment]
Est-ce que tu es capable de reproduire le problème des questionnaires vides avec des nouvelles inspections?

**Comment by jocelyncardinal** [comment]
Non désolé , je comprends pas comment ça se fait que c’est arrivé... ça rapport avec le fait que j’ai utilisé caucatown peut-être? Je vais refaire des tests et te revenir...
