### ISSUE TITLE
Possibility to add Fire hydrant 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#557]
![Capture d’écran, le 2019-07-09 à 20.16.19 copie.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4e682e81-13c9-4765-abde-56180daac0db)

**Comment by iamkinetic** [comment]
Les bornes doivent être gérées dans le logiciel CAUCA lorsque SURVI-Prévention fonctionne avec ses données.

**Comment by iamkinetic** [comment]
Ou dans Première Ligne.
