### ISSUE TITLE
Sometime fields are already filled when creating a new user

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#558]
**Describe the bug**
Sometime fields are already filled when creating a new user

![Capture d’écran, le 2019-06-18 à 15.13.26.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/ab72c6fe-3a38-44f1-94f9-252d6bdc80f4)

**WORKAROUND**
Simply close the window and try again (very easy)

**Comment by iamkinetic** [comment]
C'est l'auto complete d u browser qui semble faire le lien avec le login du site.

**Comment by jocelyncardinal** [comment]
bon points! J'avais pas pensé a ca

**Comment by iamkinetic** [comment]
To fix: try to prevent Chrome or Safary AutoFill using this strategy:

<input type="text" name="somethingAutofillDoesntKnow" autocomplete="doNotAutoComplete" />
* A different name;
* Set aucomplete to doNetAutoComplete

**Comment by iamkinetic** [comment]
It may not be possible to fix this issue, though.

**Comment by iamkinetic** [comment]
PRE-427
