### ISSUE TITLE
New user in Permission view has to be deleted first (not a bug)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#559]
**Describe the bug**
This is not really a bug but the behavior is bizarre. After new user has been created, it appear in Permission view but has to be deleted first to become available for "adding" dialog box

![Capture d’écran, le 2019-06-18 à 15.06.05.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cce4f24b-eb20-4ce5-8c49-8124a71fb035)

**WORKAROUD**
Simply delete the user in permission view and then it become available for "adding" dialog box

**Comment by iamkinetic** [comment]
Solution réelle: utiliser Cause.SecurityManagement et la nouvelle structure de sécurité pour remplacer celle de SURVI-Prévention tel que mentionné dans un autre point.

**Comment by iamkinetic** [comment]
To fix: refresh user list when leaving the user tab.

**Comment by iamkinetic** [comment]
PRE-426

**Comment by yjacques940** [comment]
Linked to #334
