### ISSUE TITLE
Add column to display SSI in users page

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#560]
**Is your feature request related to a problem? Please describe.**
There will be many users and it would be useful to be able to filter by SSI in users page

**Describe the solution you'd like**
Add column to display SSI in users page

![Capture d’écran, le 2019-06-04 à 12.07.51.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5a14feb9-b64a-4fdf-bc08-5b6995781ad6)

**Comment by iamkinetic** [comment]
@jocelyncardinal Filtrer par SSI disponible sur l'usager?
