### ISSUE TITLE
Statistique page - Get rid of door hangs data (Accroche-porte)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#561]
**Describe the bug**
Upon absence, the door hangs information is useless ans confusing in Statistique page (feedback)

**To Reproduce**
![Capture d’écran, le 2019-06-04 à 11.34.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fe737a31-16d7-48b8-952b-5e3c93f8baba)

**Comment by jocelyncardinal** [comment]
Frédéric, this is one that could be done by Audrey in August (very easy to do) - Let discuss it thursday, july 25

**Comment by iamkinetic** [comment]
Can I get a bit more details about this one?

**Comment by jocelyncardinal** [comment]
Il s'agit simplement d'enlever le nombres d'accroche du graphique en pointe de tarte ...

![Capture d’écran, le 2019-08-22 à 20.33.49.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/c60d9621-a585-4c1d-8306-5dfdb3fe9a86)

Ainsi, dans l'exemple ci-dessus, le total de visite est de 58+7=65 (et non pas 58+7+40 = 105).  Les pourcentage devienne donc 58 (89%) et 7 (11%)

**Comment by jocelyncardinal** [comment]
En ce qui concerne le code, selon Audrey ca ne devrait pas etre difficile a faire car il s'Agit de supprimer quelques lignes de code

1. Enlever la lecture des accroches porte de la base de données
2. Enlever la variable accroche-porte coté serveur et site web
3. Supprimer la catégorie accroche-porte de la configuration du graphique

**Comment by iamkinetic** [comment]
@jocelyncardinal si un bâtiment a eu 3 visites (deux absences + une visite complètes) pour une seule inspection, est-ce que ça compte pour trois ou pour un dans cette tarte?

**Comment by iamkinetic** [comment]
En tk je vais me contenter d'enlever les accroche-porte des statistiques sans toucher au reste comme indiqué.

**Comment by jocelyncardinal** [comment]
Ca compte pour 1 seule visite. Visite = bâtiment visité indépendamment que le citoyen soit absent, présent ou qu’il aille refusé. Les pompiers veulent comptabiliser le nombre de bâtiments visités et non pas le nombre de fois qu’il se sont déplacés (1 seule visite par bâtiment peut être comptabilisé). Note qu’en général, il se déplace seulement une fois même si y avait absence (il vont laisser un accroche-porte) et revenir seulement si citoyen les contacts (dans ce cas la seconde visite ne sera pas additionnée car déjà comptabilisée - seulement le statu changera de Absence à Visite complète)

Le 4 sept. 2019 à 13:38, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jocelyncardinal<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7Cbf42d511609c47078ba708d7315ea522%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637032154869369169&sdata=8Ob29yRctQA1LrGo2zcIRX%2BbOsk4M3AnAVM4aitEino%3D&reserved=0> si un bâtiment a eu 3 visites (deux absences + une visite complètes) pour une seule inspection, est-ce que ça compte pour trois ou pour un dans cette tarte?
