### ISSUE TITLE
Problem to keep (save) the data in Questionnaire page

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#562]
**Describe the bug**
Problem to keep (save) the data in Questionnaire page

**To Reproduce**
I dont know how to reproduce see this screenshot ...
![Capture d’écran, le 2019-05-13 à 10.25.29.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fc2cfe54-6c45-4aa8-98e3-61a524338765)

**WORKAROUND**
Redo the modification and click somewhere else

**Comment by jocelyncardinal** [comment]
![Capture d’écran, le 2019-06-03 à 12.59.18.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/b60a79b5-3f59-4a25-b66d-5ffff17d84f3)

**Comment by iamkinetic** [comment]
I have not reproduced this issue.  Feel free to create a new issue when you find out how to reproduce the issue.
