### ISSUE TITLE
Report - Problem with @MainBuildingFireHydrant.Address@

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip#563]
**Describe the bug**
@MainBuildingFireHydrant.Address@ display a POINT instead of a address

**To Reproduce**
![Capture d’écran, le 2019-05-24 à 11.10.53.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/2fbab782-14dc-4725-9fc8-50705ab752fb)

![Capture d’écran, le 2019-07-23 à 18.08.48.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/8484e3a1-8781-4689-931b-e16c49650582)

**Comment by iamkinetic** [comment]
Parce que la très grande majorité des bornes ne sont identifiées que par leur coordonnées dans Première Ligne/Logiciel Cauca.

**Comment by iamkinetic** [comment]
Si la borne est identifiée par une adresse, c'est ce qui sera affiché.  Si la borne n'a que des coordonnées, c'est ce qu'on va afficher.  C'est le cas dans cet exemple.
