### ISSUE TITLE
User: department and group filter are not working.

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#567]
**Describe the bug**
The fire safety departement and the group's columns filter don't work in the user's page.

**To Reproduce**
1. Go to 'system management'
2. Click on 'user'
3. Enter text in the 'fire safety department' or 'group' columns

Same problem in the group's page when searching the group by user name.

**Expected behavior**
Grid filtered on entered values.  Just like the filter for the risk level's column in Risk Level By Department's page.

**Comment by yjacques940** [comment]
Lorsque je supprime des usagers, ça laisse des trous dans la liste des utilisateurs du groupe:
image
![image](https://user-images.githubusercontent.com/40217275/65425283-a0fca900-dddb-11e9-9db1-94e544ff3759.png)
