### ISSUE TITLE
New user display fire services and groups of the previous user opened

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#575]
**Describe the bug**
The emergensy services and groups are not always empty on a new user:

**To Reproduce**
 -> Open an existing user already set up
 -> Close the edit form
 -> Create new user
 -> the fire services and the group display the set up of the existing user.

**Expected behavior**
the form of the new user must be empty, except for default values

**Screenshots**
![new user fire services and groups](https://user-images.githubusercontent.com/38532918/65989375-8ff50d00-e457-11e9-9ce0-586136ce96b4.png)

**Other problems*
The user permission show an unchanged status on a new user, it should display a false value by default.
![new user permission](https://user-images.githubusercontent.com/38532918/65989044-f2014280-e456-11e9-98cf-87db8a0b4f94.png)

**Comment by iamkinetic** [comment]
@yjacques940 Et lui?

**Comment by yjacques940** [comment]
Corrigé.
