### ISSUE TITLE
Refresh data on cancel action

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip#66]
When changing data for null or new value the grid binded take the change even on cancel action so you have to refresh the page to see that nothing have been change.
Modification : 
 - Call refresh on cancel action

**Comment by philipperobertgh** [comment]
Error of validation : 
 - When creating a new item(road) if you are set up to french and only add english name the validation of null value doesn't work
 - On delete call a refresh
     -> when deleted an item it disappear from the list but on refresh the item is back with unactive state

**Comment by iamkinetic** [comment]
Philippe mentionnait ça : 

Error of validation :

- On french setting i can put only english name and null validation doesn't work
- With no french name the required warning in the add popup work only when switching tabs
- On delete call a refresh
   -> when deleted an item it disappear from the list but on refresh the item is back with unactive state
- Updating the active control doesn't work, no error showed but save is not working

Est-ce que tout ça est supposé être réglé?

**Comment by iamkinetic** [comment]
Je teste avec les voies :
* Si je crée une nouvelle voie et que j'entre seulement un nom français et que je fais save, ça ne save pas et je n'ai pas le warning visuel pour le nom anglais manquant.
* Si je crée une nouvelle voie et que j'entre seulement un nom anglais et que je fais save, ça ne save pas et je n'ai pas le warning visuel pour le nom français manquant.
* J'avais pas vraiment allumé avant, mais on ne devrait pas voir les entities inactifs et on ne devrait pas permettre d'éditer le champ actif dans les différentes fenêtres.
